### ISSUE TITLE
idempotency of registration

### ISSUE THREAD

**Issue by petervanderstok** [core-wg/resource-directory#111]
should we add some text to clarify the idempotency consequences?

**Comment by chrysn** [comment]
I think that the new text is needlessly restrictive (see more general comment in <https://mailarchive.ietf.org/arch/msg/core/jek5vApeH1gbb_u4JsgUkb7bD80> w/rt "Why are we requiring idempotency?").

**Comment by chrysn** [comment]
The text has been updated to describe the idempotency requirements better.

Note about location changing: The location of a registration could change only if a client uses the registration interface again (and then, by idempotency rules, only if some parameters changed or probably the RD as a whole changed). Clients that update as they preferably should (by doing a registration update) never receive a new location.
