### ISSUE TITLE
can hosts relation value change context in update

### ISSUE THREAD

**Issue by petervanderstok** [core-wg/resource-directory#114]
6.  Inferred context based on source IP when an update is done.  If no
con is provided, is that supposed to be checked again to see if it is
"right"?
Only if we did the infer to begin with?

My interpretation of the current text is:
When a  registration is done with the same ep and d values, the old
registration is removed and a new one with the new parameter values is
created at a new location.
That means that the value of con
is specified in the registration without any memory of earlier values.

This is not the sequence that I was looking for.

POST /rd?ep=node1
   - payload contains the set of resources the register.
   - returns a location of /rd/yyyy

POST /rd/yyyy?ep=node1
   - payload is empty.

In the first post, the rd will infer a context based on how the registration
is done.  The second post just says that the TTL value is to be refreshed
back to the life-time value.  However, the inferred context could also be
changed.

Thanks for the example; it would take me long to figure this out otherwise.

Reading the update specification, the ep=node1 is illegal in the update. Specifying ep means creating a new registration.

sending the update
POST /rd/yyy will update the lt value.
It is allowed to change the value of con in the update POST specification.
The question is:
When an updating ep, different from the registering one, sends the update of lt, does the context change to the hosts relation value of the updating ep.

My gut reaction is no. it does not change the context value in the RD because that needs an explicit ?con= in the update specification.

A warning in the RD text to this effect looks reasonable.

**Comment by chrysn** [comment]
Currently, con= on every update until it is first set explicitly, and I think it should stay that way; see <https://mailarchive.ietf.org/arch/msg/core/jek5vApeH1gbb_u4JsgUkb7bD80> for details.

**Comment by jimsch** [comment]
I do not currently distinguish between an implicit set of the con or anchor attributes as opposed to an implicit set of them.  This would need to be made explicit.  I can see why this might be useful.  If you register both coap and coaps addresses with one set using an explicit con and the other an implicit con.  Then it becomes important to make sure that the update is always done with the "right" protocol.  This might be a good example to clarify in the document.

**Comment by chrysn** [comment]
Should work with the updated text.

@jimsch w/rt coap and coaps: In a plain RD, you can only ever have one address per endpoint; protocol-negotiation will introduce additional parameters for multiple and describe how they'll work.

**Comment by jimsch** [comment]
I was actually looking at doing two different registrations, one coap and a separate one for coaps.  I was then looking at the explicit vs implicit set of con and what it would mean if the first pair of registrations is done w/ and implicit con and then do the same thing w/ and explicit con and then do with the implicit (or not set) cons.  I think that this would work correctly as the doc is specified.
