### ISSUE TITLE
accept option simple registration

### ISSUE THREAD

**Issue by petervanderstok** [core-wg/resource-directory#115]
7.  I don't understand the presence of the content-format for the
empty message posted for simple registration.  This seems to be odd if
the content is empty.

content-format is specified such that RD knows what content-format to
request.

Would accept be a better option to use?  This would allow for more than one
value to be specified.

Agree.

**Comment by petervanderstok** [comment]
specified accept option template for request interfaces: RD->ep and ep->Rd template

**Comment by chrysn** [comment]
Sorry, but neither Accept nor Content-Format works that way; they have defined meanings and that's neither. The server will need to make an initial guessed attempt or just try without Accept (when getting .well-known/core) and trust that it knows more link serializations than the constrained node.

The new commit (see link below) does not close this issue to keep it visible, @petervanderstok please close if you agree with my change.

**Comment by petervanderstok** [comment]
and how to do reporter OK? I agree with the removals up to a point.
What about solving the issue of ct acceptance?
