### ISSUE TITLE
template for simple registration

### ISSUE THREAD

**Issue by petervanderstok** [core-wg/resource-directory#116]
8  Is there supposed to be a way for simple registration to return an
error message?  As written this is not necessarily done.
Specifically, the response to the post can be executed before the
query to /.well-known/core is done and the registration is attempted.

I see what you mean: also the return of 2.04 shows in the example but not
in
the specification.
This warrants additional text to specify the simple registration text.

will add the simple registration template to the text.

**Comment by petervanderstok** [comment]
Added template in section 5.3.1. simple registration

**Comment by chrysn** [comment]
Ad "GET /.well-known/core":

Our templates are already verbose, redundant with CoAP ("4.00 Bad Request and 400 Bad Request: Malformed request.", surprise) and at the same time not exhaustive (see <https://github.com/core-wg/resource-directory/issues/6>); I've come to accept that.

But the GET section on the endpoint's .well-known/core is the very functionality that is described in RFC6690 Section 4. What is gained by duplicating that specification and selectively picking some possible error codes?

I suggest we remove that part.

Ad simple registration interface: Any particular reason you picked precisely ep and d to be eligible? lt definitely makes sense, and so do extra-attrs (they are our extension point, and not having them would exclude simple registration from extensibility).

A pull request to that respect is pending (see link below) together with <https://github.com/core-wg/resource-directory/issues/121>.

**Comment by chrysn** [comment]
I think that's in a good state now with #127, #135, and the separator paragraph before the GET operation in #simple.

I might have missed the point of this issue though, so not closing right away; @petervanderstok please close if you think this issue is done.
