### ISSUE TITLE
General relevance of ep as a unique identifier

### ISSUE THREAD

**Issue by chrysn** [core-wg/resource-directory#120]
The general relevance of the ep attribute is under discussion at <https://mailarchive.ietf.org/arch/msg/core/kNGJgkIQF7ZqXLYJFNq4LGXuBs0>; this is a tracking issue that thread.

My summary: "It's not clear to people what the ep attribute is and how it is tied to security. It might be better for regular operation that it is not expressed explicitly but always taken from the security context. (But how is it expressed and used in lookup?)"

**Comment by petervanderstok** [comment]
My conclusion:
This is not really an RD issue, but a security extension to the RD using authorization server.
Fr very small AS tokens it is preferable that the ep value is equal to the security identifier.
For some users (e.g. building control) it is important to use ep values that have a meaning with respect to the names of installation components.
In that case, a larger AS token may include the ep name and the security identifier (plus the d= value)

**Comment by petervanderstok** [comment]
no  more comments on current security policy text
