### ISSUE TITLE
Uniqueness scope for `ins`

### ISSUE THREAD

**Issue by chrysn** [core-wg/resource-directory#13]
Within which scope should the `ins` parameter be unique?

The -09 draft (and the restoration PR #11) demands that it SHOULD be unique across all resources with the same `rt` and `d`. That is hard for the individual device to support out of the box short of adding its serial number to everything, and (given it's not a MUST) still insufficient for an RD exporter (eg. to DNS-SD) to use.

In the last meeting, labels for distinguishing two instances in a combined devices came up (two fridge compartments, `ins="upper"` and `ins="lower"`), which would violate that constraint when two fridges are present in one domain.

I'd suggest to either relax the uniqueness requirements and have whoever exports this to DNS-SD deal with the resulting ambiguities[1], or make them strict enough for ins= conflicts to fail early (an absent ins= would be such a conflict too, or is that a free pass to construct an `ins` at will?), and suggest a different mechanism for "upper"/"lower" distinctions (title?).

[1]: For example, as is done in the Z-Wave-IP, see design specification 4.1.2.3: "If several End Point Name and End Point Location entries are identical, the Z/IP RD MUST auto-append unique data to each of the conflicting End Point Names"

**Comment by chrysn** [comment]
Taken to the mailing list at https://mailarchive.ietf.org/arch/msg/core/Hk_RMM1eku-vdXl3wIm0Nu7lKCk

**Comment by chrysn** [comment]
I just tried inserting the proposed text from https://mailarchive.ietf.org/arch/msg/core/Hk_RMM1eku-vdXl3wIm0Nu7lKCk into the draft, but the more I think of it, either becomes the "title", or becomes a vehicle of transporting information so particular to DNS-SD that it should be defined there.

Suggestions on how to proceed here would be very much appreciated.

**Comment by petervanderstok** [comment]
Hi all,

> I just tried inserting the proposed text from
    The resource instance attribute "ins" is a textual parameter that
     can be used to distinguish between resources of equal resource
     types within an endpoint or a domain.

     For example, values can be texts like "Ceiling light, Room 3", "Slot
     2", short IDs like "AF39", but also UUIDs or iNumbers.

> into the draft, but the more I think of it, either becomes the
> "title", or becomes a vehicle of transporting information so
> particular to DNS-SD that it should be defined there.

I agree that the uniqueness of ins should not be in, as exemplified in 
my earlier mail.
Further, it was always the intention that an "agent" would map the RD 
contents to DNS-SD.
Other agents can map to other discovery institutes.

It is up to the agent to solve uniqueness problems if they exist.

I propose a different text for ins:
     The resource instance attribute "ins" is a textual parameter that
     can be used to present the resource with a name that is more 
amenable
     for later reference in a given context.

     For example, in the context of an office, values can be texts like 
"Ceiling light, Room 3", "Slot
     2",  in the context of automatic installations: UUIDs or iNumbers, 
or in the context of human use:
     "Peter's phone", "TV in living room".

Hope that helps to converge on text.

Peter

**Comment by chrysn** [comment]
The RD will not enforce that uniqueness, as the DNS-SD publisher has to deal with conflicts anyway.

**Comment by cabo** [comment]
I agree that this is the correct answer.

However, I'm curious how the DNS-SD publisher then pushes back the conflict to the RD.  Can it make the client register a different `ins` value?   Or, if it changes the value on its own, can it inform the client that the value was changed?

**Comment by chrysn** [comment]
A DNS-SD publisher receiving data from a generic RD will need to accept failure based on what the RD-DNS-SD document can describe within its scope.

For setups that require that this won't happen, I see two ways forward:
* RD-DNS-SD can specify (when registering the `ins` property) that an RD can reject duplicate registrations within a (d, rt) partition. If an RD is `ins`-aware or is a publisher itself, the problem gets pushed back to the client, so it will enter a failure state because it is presumably misconfigured, and whichever management tools are used site-wide can respond to the issue. (Were I to implement such a thing centered around the RD, I might even take the liberty to reassign such failing registrations into a special error domain for debugging purposes).
* The DNS-SD publisher could try to take further actions, eg. by looking for a CoMI endpoint that exposes the instance name and suggest a better one there, but such a mechanism would be out of scope even for RD-DNS-SD.

**Comment by petervanderstok** [comment]
Indeed there may be additional syntactic requirements on the RD by 
adding the registration of ins and exp.
I assume that will become part of the rd-dns-sd standard added to the RD 
standard.
In other words, one can acquire a standard RD, or a DNS-enabled RD with 
additional restrictions.

Anyway, it is foreseen that a special agent handles the RD to DNS 
conversion, apart from the RD.
and a mapping from RD entries to DNS is proposed, but will certainly be 
improved given the interest.

Peter

chrysn schreef op 2017-10-26 16:11:
