### ISSUE TITLE
Simple registration: allow or forbid optimistic success response

### ISSUE THREAD

**Issue by chrysn** [core-wg/resource-directory#130]
Two of the current implementations have different behavior when it comes to simple registrations:

* Jim's sends an ACK, but belays the Success response to when the .well-known/core has been obtained.
* Mine sends Success anyway to acknowledge the EP's intent to register, and only logs an error if something later goes wrong.

I think that Jim's is the better behavior; mine was motivated by consideration for clients that have a limited number of open exchanges (1), and might answer 5.03 for as long as they have outstanding CONs themselves.

IMO we should either prescribe Jim's behavior or add a warning that the Success indication does not necessarily mean too much. Which would you prefer?

**Comment by petervanderstok** [comment]
I prefer the success return, and having understood that things are out of control for the registering node.
Option 2 involves keeping channels open, and for how long?, are retries possible?
We are discussing here very low power, always sleeping nodes. Without a proxy their life is impossible anyway.

**Comment by chrysn** [comment]
I've written conflicting PRs to either allow both (#134) or prescribe immediate responses (#135). Either would be fine with me, "prescribe fetch-then-respond" does not sound like a consensus candidate from the comments.

@petervanderstok and other authors: any preferences? I have a slight preference for accept-both.
