### ISSUE TITLE
resource type for registration resources

### ISSUE THREAD

**Issue by chrysn** [core-wg/resource-directory#141]
This was discussed in the last meeting but did not result in an action item; will check whether we agreed to do this (AFAIR we did) and add the text for it.

**Comment by petervanderstok** [comment]
The right place is in the management example. I hesitated but did not do
it
chrysn schreef op 2018-06-27 11:51:

> This was discussed in the last meeting but did not result in an action item; will check whether we agreed to do this (AFAIR we did) and add the text for it. 
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1] https://github.com/core-wg/resource-directory/issues/141
[2]

**Comment by chrysn** [comment]
Done with #146 in 801a4352587f4354d57949ab7cb427600a139158.
