### ISSUE TITLE
Is rd-lookup-* optional?

### ISSUE THREAD

**Issue by mjkoster** [core-wg/resource-directory#15]
The text in section 7 says lookup is optional but the table in section 7 lists two mandatory lookup resource types. I can't find text to explain the difference.

**Comment by petervanderstok** [comment]
Hi michael

What is section 7?RD Lookup {#lookup}? And I cannot find the table.

However, I can imagine an optional interface, but once the interface 
exists, some attributes are mandatory.

Peter

Michael Koster schreef op 2017-05-05 15:53:

**Comment by chrysn** [comment]
I'd interpret that as "it is optional to implement lookup, but if lookup is implemented, res and ep lookup must be provided, and d and gp may be."

**Comment by petervanderstok** [comment]
Hi all,

the more I look at this piece of text:
    "In order for an RD to be used for discovering resources registered
    with it, an optional lookup interface may be provided. "

The more it looks kafkian to me.
The purpose of the RD is to be able to do lookups;
Without it, it becomes a bit like a write-only conference, or a shop 
without customer facilities.

One might argue that the filtering is a bit cumbersome.
Making filtering optional seems reasonable.

Peter


chrysn schreef op 2017-05-09 12:23:

**Comment by chrysn** [comment]
I think that this is to allow vendors to use RD for registration, but only use the data internally or expose them with a different interface. (AFAICT, that's what's happening in LWM2M).

If we want to mandate lookup, I suppose that needs to go through the core mailing list?

**Comment by chrysn** [comment]
Sent to core list at https://mailarchive.ietf.org/arch/msg/core/V0VqYAbMMyW8fc4ceHOrqAOoclE
