### ISSUE TITLE
base also for anchor?

### ISSUE THREAD

**Issue by petervanderstok** [core-wg/resource-directory#159]
I noticed that in A.1, registration update, the base is modified.
This works OK for the link href, but also for the anchor that has been resolved?

For example
Register: <t>;anchor="sensors/temp"
They are resolved to <coap://[myip]/t; anchor="coap://[myip]/sensors/temp

Now do a registration update: with base=coaps://[newIP]
I assume both anchor and href are involved and in lookup we see:
<coaps://[newIP]/t; anchor="coaps://[newIP]/sensors/temp.

The current text is not very clear about this.

**Comment by chrysn** [comment]
Fixed in 423280c38eefce3161c87ec5bbf13a7425a78ca7
