### ISSUE TITLE
Avoiding link-local addresses

### ISSUE THREAD

**Issue by chrysn** [core-wg/resource-directory#165]
Today's plug test gave us a <coap://[fe80::2c7c:b7ff:feac:bda8%tapbr0]/sensors/temp> address as a result of (manual simulation of) a "Finding" step yielded a link-local address, and simple registration was performed to that.

We might want to add in the finding steps that link-local addresses should be avoided, and maybe  that RDs that can be found via such addresses might want to refuse such registrations unless they have some very explicit knowledge that'd allow them to translate the addresses -- though the latter is probably overly specific.

I'm not familiar enough with the interaction of multicast addresses with link-local addresses, that'll need some research. In my practical experiments, registrants have not used any `::1` or `fe80:` to talk to multicast addresses even though it would have worked, but I only tried ff05 addresses so far and will try more.

(The most worrysome case to me seems to be a simple client doing a `POST coap://[ff02::fd]/.wk/c?ep=mynode`, but I don't think we allow that anyway. The next most worrysome is the same client doing a `GET coap://[ff02::fd]/.wk/c?rt=core.rd`, receiving a response from a fe80 address, and then doing simple registration there. Will experiment...)

**Comment by chrysn** [comment]
I've now tried out lookups to ff05::fd (site-local) and ff02::fd (link-local) using aiocoap on Linux in a network where a global address, a ULA address and a link local address were available.

The site-local lookup used the global address, but the link-local lookup did result in fe80 addresses being seen by the RD. That means that the entry can only be dereferenced by the RD itself unless an explicit base address is passed.

For explicitly configured address and SLAAC/DHCP it should suffice to caution operators against advertising link-local addresses.

For the 6LBR I can't tell -- is there any danger of nodes knowing their 6LBR by a link-local address, eg. in mesh-under networks, and if so, can it know a routable address of it as well? @cabo, can you answer that?

DNS-SD appears to gives me a wild mixture of ULA, global addresses and link-local addresses (but link-local only on interfaces w/o routable ones?) from peeking into my local console, but given that's only an example, some general words of warning might suffice here.

For multicast, I'd change the text such that lookup would be done using site-local fd05:: addresses in the suggested heuristic -- and that RDs that still want to answer  link-local requests should advertise their services with full URIs containing routable addresses.

I'm toying with the idea of extending "If the registrant-ep uses an ephemeral port to register with, (then base is required)" to ", or if the registration happens using addresses that are not routable" -- given that like the ephemeral ports, the requester URI can be *expressed* by the RD but not *used* by anyone else. (TCP to host:9234 will be refused, IP to fe80::f00:ba5%wlan0 has no such interface in other devices).

**Comment by chrysn** [comment]
I have done some more experiments and found out that it *is* possible to target a link-local multicast with routable source addresses. Same goes for sending to link-local addresses from routable source addresses. (It is just tricky to do on a POSIX system as you need to know a usable local address beforehand.)

Concrete text proposals therefore are:

* Where describing base, add: "If the registrant-ep uses an ephemeral port to register with, *or if the registration happens using addresses that are not routable*, it MUST include the base..."
* (After the confifgured/network provided section): "Operators should pick global or at least routable addresses for preconfiguration or network provided defaults, as this makes it easier for registrants to send from a suitable source address."
* (After the heuristics and rate-limiting paragraph): "Registrant implementations that have limited control over the source addresses should prefer heuristic steps for which they'll use routable addresses over, for example, link-local multicast. Thus, they can avoid finding an address of the RD for which they would need to explicitly set their base address later."

The first point would already avoid the problem we've run into at the interop (the registration would have been denied in the first place), the rest is only guidance to implementors (therefore no capitalized "SHOULD"s) which I'd be happy to move into other parts (or could also leave out) if there are better suggestions.

**Comment by chrysn** [comment]
Did you run manage your devices with any protocol that involves IP literal URIs?

Thing is: even if one tried to run an RD link-locally, the RD would report addresses like `coap://[fe80::42%eth0]`, and the lookup client in general has no eth0 device, nor has eth0 any meaning for it – best they could do is drop the information and assume it's link-local to their primary interface, and that's a very far stretch.

**Comment by chrysn** [comment]
Note also that what we're doing in RD lookups and base addresses to form coap://[fe80::42%eth0] style addresses is not something that's actually covered by RFC3986. It's just something that many implementations do in order to have something they can round-trip into a URI locally (so you can

**Comment by petervanderstok** [comment]
Consequently, This is not a link-local feature but a general one.
And we should add some text that all characters after % and including %
MUST be removed from the address part of the URI before it is stored as
the BASE..

Peter
chrysn schreef op 2018-11-14 11:27:

> (Correcting myself after doing some research prompted by Peter: There _is_ a way to express zone identifiers in URIs per the RFC6874 [1] update to 3986, but in formalizing it notes that these URIs can not be passed around). 
> 
> --
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub [2], or mute the thread [3].
 

Links:
------
[1] https://tools.ietf.org/html/rfc6874
[2]
https://github.com/core-wg/resource-directory/issues/165#issuecomment-438613770
[3]

**Comment by petervanderstok** [comment]
Hi Christian,

What about adding a section 5.2 with title "URI schema parsing"
That section describes that a URI schema can contain the DNS name with
port as specified in RFC4501, or contain an IP literal with port. RFC
3986 specifies that when IP literals are used the IP address can be
followed by a % sign followed by a zone identifier. The %zone part must
be stripped from the schema before being used and stored in the RD.

What about my suggestion to start an appendix E, with reference from
5.1, to describe the additions for future link serializations?

Do you want me to provide some text into the github?

Greetings,

Peter
Peter van der Stok schreef op 2018-11-14 12:04:

> Consequently, This is not a link-local feature but a general one.
> And we should add some text that all characters after % and including % MUST be removed from the address part of the URI before it is stored as the BASE..
> 
> Peter
> chrysn schreef op 2018-11-14 11:27:
> 
>> (Correcting myself after doing some research prompted by Peter: There _is_ a way to express zone identifiers in URIs per the RFC6874 [1] update to 3986, but in formalizing it notes that these URIs can not be passed around). 
>> 
>> --
>> You are receiving this because you commented.
>> Reply to this email directly, view it on GitHub [2], or mute the thread [3].
 

Links:
------
[1] https://tools.ietf.org/html/rfc6874
[2]
https://github.com/core-wg/resource-directory/issues/165#issuecomment-438613770
[3]

**Comment by cabo** [comment]
Zone identifiers are locally significant to a specific system.  There is no point in sending a URI to a different system that has a zone identifier in it, as it has no way to interpret it (it would simply not be a "Uniform" resource identifier outside the originating system).  Since the RD is meant to exchange URIs between different systems, I cannot imagine a usage where zone identifiers make sense in an RD.  So I would disallow them.

The other question is whether link-local addresses without zone identifiers might be useful in an RD.  We should probably explain that this requires the server for that URI and the client of the RD (the RD-internal application or a lookup client) to have context that allows applying the link-local address to a specific link.  Most likely, this is only going to work if the RD is on the same link.  In this case, if the RD is on more than one link, the RD might want to qualify the RD entries internally as to which link is meant (e.g., using one of its own zone identifiers internally) and only hand out the link (without zone identifier!) to clients that also are on that link.   Do we want to include/describe that scenario?

**Comment by chrysn** [comment]
(For reference: Peter's update to that topic was in 32dd0d04389288678e93f4af6c4603ca7c780de0).

I'm not happy with that proposal; it suggests that implementors could just drop the zone extension, while this is something is will fail unless all devices involved are aware that they're not dealing with Universal but only with link-local Resource Locators, and is therefore (if ever) only an acceptable solution in very well-controlled circumstances. Sketching up an alternative proposal that would still allow it (as you insist, I do think it's a bad idea), but gives people the right direction to get a working setup in general.

**Comment by chrysn** [comment]
A proposal that recommends against doing it but still allows your stripping is uploaded as 33e97695b2c5270e8cb4080cbeb36b63548a8af2 (sorry, it refers to the wrong issue). Would that work for you?

**Comment by chrysn** [comment]
Based on the last mails exchanged and comments in https://github.com/core-wg/resource-directory/commit/33e97695b2c5270e8cb4080cbeb36b63548a8af2#r31701824, I've added fccaf662910d0ab58585b13101e1546aa7b7fea3 removing the vague "RD setups" term and the section on "if everyone agrees it's OK, you can do it otherwise" (for that's always the case), and close this.

Please comment here or on the commit if there are still open questions.

**Comment by petervanderstok** [comment]
3.4.  Link-local addresses

Suggest to change title to "zone identifiers"; and change one sentence
OLD
"Therefore, RD servers SHOULD reject registrations which use of URIs containing link-local IP addresses."
NEW
Therefore, RD servers MUST not distribute registrations which contain zone identifiers in the .Registration Base URI.

**Comment by chrysn** [comment]
As much as I'm a fan of small changes, the only consensus that has been reached on the current linklocal section was between the two of us based on my skewed view of the topic.

The suggestion I'm submitting as bdfecd17c161f3b45f85dfce30125c8c24c4b0b3 is a rewrite of that section, and hopefully places the statements at the right positions (motivation / guidance in the architecture section, normative statements in the interfaces they belong to.)

Short of one brief comment this text avoids the topic of how clients need to handle URIs with link-local addresses; that's a topic for LWIG or other clarification documents.

I'm open as to whether mismatching items in endpoint lookups should be hidden completely, or should just not have their base attribute visible.

**Comment by chrysn** [comment]
(One more thing that just got to my mind: It's saying saying that in registrations, "base MUST NOT contain a zone identifier". CTs are not my forte; if you envision that a CT could know that there's a link-local and know the RD's zones, that could become a SHOULD. The wording in the lookup section is such that the zone identifiers would still not be visible.)

**Comment by cabo** [comment]
Zone identifiers are local to a system. It never makes sense to use them in URIs exchanged between systems.  I don't understand your CT scenario.

**Comment by chrysn** [comment]
The CT scenario assumes that the CT knows a lot about the whole setup, including the RD's interface identifiers (after all, they come over in the document as being quite well-informed), and can thus do a 3rd party registration for a LL-only device even though it's far away from the RD.

If that's a bad idea, never mind.

**Comment by petervanderstok** [comment]
It's not a bad idea but a necessary one

Peter
chrysn schreef op 2018-12-21 15:08:

> The CT scenario assumes that the CT knows a lot about the whole setup, including the RD's interface identifiers (after all, they come over in the document as being quite well-informed), and can thus do a 3rd party registration for a LL-only device even though it's far away from the RD. 
> 
> If that's a bad idea, never mind. 
> 
> --
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/core-wg/resource-directory/issues/165#issuecomment-449397655
[2]

**Comment by petervanderstok** [comment]
good thinking, but  very unlikely.
I don't see zone identifiers being used (specified) by the CT

Peter
chrysn schreef op 2018-12-21 14:58:

> (One more thing that just got to my mind: It's saying saying that in registrations, "base MUST NOT contain a zone identifier". CTs are not my forte; if you envision that a CT could know that there's a link-local and know the RD's zones, that could become a SHOULD. The wording in the lookup section is such that the zone identifiers would still not be visible.) 
> 
> --
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/core-wg/resource-directory/issues/165#issuecomment-449395250
[2]

**Comment by chrysn** [comment]
@petervanderstok I'm confused because both your last comments relate to the same idea (that a CT would go `POST /rd?ep=light142&base=coap://[fe80::42]%eth3` towards an RD where it know that said light is link-local to the RD's eth3).

**Comment by petervanderstok** [comment]
I understand your confusion; and so am I.

Until recently I was unaware of the zone identifiers.
May be I was unclear or understood  a different question from the one
you posed.

To be clear:
a CT will specify link-local addresses in the base.
It is very unlikely that it specifies the zones.
Zones are more a network management issue than an application management
issue.
That's what I tried to point out in the lighting example by having two
naming entities:
network management and lighting application management.

Peter
chrysn schreef op 2018-12-21 15:36:

> @petervanderstok [1] I'm confused because both your last comments relate to the same idea (that a CT would go POST /rd?ep=light142&base=coap://[fe80::42]%eth3 towards an RD where it know that said light is link-local to the RD's eth3). 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [2], or mute the thread [3].
 

Links:
------
[1] https://github.com/petervanderstok
[2]
https://github.com/core-wg/resource-directory/issues/165#issuecomment-449404373
[3]

**Comment by chrysn** [comment]
> a CT will specify link-local addresses in the base.
> It is very unlikely that it specifies the zones.

If it specifies link-local addresses in the base, the RD will need to know which zone they relate to. That zone information would normally come from the zone of the received request, but the CT is (I'd assume) stationary, and can't make messages appear at the local RD's WiFi interface.

A stationary CT can thus either not register local EPs (basically, as it would have before we opened this can of worms), or needs to know how the RD names its zones (which might work but might be abusing the system).

If it's unlikely, we can just drop that sub-topic. If it's necessary, we'll have to think it through.

**Comment by petervanderstok** [comment]
I fail to understand.
AFAIK:
zones are nor compulsory in the addressing.
When a node specifies the link-local address of a destination, there is
no obligation to specify the zone. Consequently, the payload of the CT
to the RD can contain L-L addresses without confusion.
The client receives the L-L addresses from the RD and uses them on the
local link without zone specification.

BTW: these local links can be very large; I met providers which deploy
only one router on their network and all the other segments are
connected by bridges connecting hundreds of nodes.

Peter
chrysn schreef op 2018-12-21 15:52:

>> a CT will specify link-local addresses in the base.
>> It is very unlikely that it specifies the zones.
> 
> If it specifies link-local addresses in the base, the RD will need to know which zone they relate to. That zone information would normally come from the zone of the received request, but the CT is (I'd assume) stationary, and can't make messages appear at the local RD's WiFi interface. 
> 
> A stationary CT can thus either not register local EPs (basically, as it would have before we opened this can of worms), or needs to know how the RD names its zones (which might work but might be abusing the system). 
> 
> If it's unlikely, we can just drop that sub-topic. If it's necessary, we'll have to think it through. 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/core-wg/resource-directory/issues/165#issuecomment-449408209
[2]

**Comment by cabo** [comment]
So let's try to flesh out the scenario.

An RD has two IoT links, one 6LoWPAN and one G.9959 (Z-Wave), as well as a link to the general Internet (or just a local WiFi; doesn't make a difference here).
The CT talks to the RD over the general Internet.   There is an FE80::1 on both IoT links, and the CT wants to register both on the RD.

* The FE80::1 hosts cannot see each other under that address.
* The RD would need to offer the Z-Wave FE80::1 to Z-Wave only, and the 6LoWPAN FE80::1 to the 6LoWPAN only.

So far, so good with the above text.

Now, how does the CT talk to the RD about the two links?  The RD may have internal zone identifiers for them, but the CT has no idea what they are.  If it did, we might imagine that the CT generates an RD-LURI (an URI with a zone identifier locally significant only to the RD) and registers the hosts with the RD that way.  RD could then strip the zone identifier when offering the Z-Wave host to the Z-Wave lookup clients and the 6LoWPAN host to the 6LoWPAN lookup clients.  An external (WiFi/general Internet) lookup client would see neither because there is no way for it to communicate with them.

So, to make this scenario work, we'd need:

1. A way for the RD to publish its zone identifiers
2. A way for the CT to somehow make sense of these zone identifiers and correlate them to knowledge it has about hosts on the link
3. We would need to allow RD-LURIs in CT registrations.

Not sure I am happy with this design, even if I had an idea how to do 1 and 2.

(A CT that is on-link to one of the IoT-links would have no problem with this scenario given the above discussion on this issue.  It just can't do the job without being on the link unless we solve 1, 2, 3.)

(I don't want to even think about DNS entries that resolve to link-local addresses...)

**Comment by petervanderstok** [comment]
Hi Carsten,

Nice try.
The networks I had in mind where L-L might be useful, are less complex
than the one below.
I think that the zone extensions are the least of your problems in your
case below.
Using routable addresses is easier and probably employed when a router
(RD?) enters the network.

Peter

cabo schreef op 2018-12-21 17:54:

> So let's try to flesh out the scenario. 
> 
> An RD has two IoT links, one 6LoWPAN and one G.9959 (Z-Wave), as well as a link to the general Internet (or just a local WiFi; doesn't make a difference here).
> The CT talks to the RD over the general Internet. There is an FE80::1 on both IoT links, and the CT wants to register both on the RD. 
> 
> * The FE80::1 hosts cannot see each other under that address.
> * The RD would need to offer the Z-Wave FE80::1 to Z-Wave only, and the 6LoWPAN FE80::1 to the 6LoWPAN only.
> 
> So far, so good with the above text. 
> 
> Now, how does the CT talk to the RD about the two links? The RD may have internal zone identifiers for them, but the CT has no idea what they are. If it did, we might imagine that the CT generates an RD-LURI (an URI with a zone identifier locally significant only to the RD) and registers the hosts with the RD that way. RD could then strip the zone identifier when offering the Z-Wave host to the Z-Wave lookup clients and the 6LoWPAN host to the 6LoWPAN lookup clients. An external (WiFi/general Internet) lookup client would see neither because there is no way for it to communicate with them. 
> 
> So, to make this scenario work, we'd need: 
> 
> * A way for the RD to publish its zone identifiers
> * A way for the CT to somehow make sense of these zone identifiers and correlate them to knowledge it has about hosts on the link
> * We would need to allow RD-LURIs in CT registrations.
> 
> Not sure I am happy with this design, even if I had an idea how to do 1 and 2. 
> 
> (A CT that is on-link to one of the IoT-links would have no problem with this scenario given the above discussion on this issue. It just can't do the job without being on the link unless we solve 1, 2, 3.) 
> 
> (I don't want to even think about DNS entries that resolve to link-local addresses...) 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/core-wg/resource-directory/issues/165#issuecomment-449440431
[2]

**Comment by petervanderstok** [comment]
Hi Christian,

The sentence below seems to cover what I want to be covered and warns
people at the same time that
multiple RD inerfaces and L-L may introduce a problem.

If Base URI contains a link-local IP literal, it MUST NOT contain a Zone
Identifier,
and MUST be local to the link on which the registration request is
received.
 merry Xmas,

Peter
chrysn schreef op 2018-12-21 17:22:

> My understanding (since yesterday's meeting, so still fresh and easily wrong) is that a host, in general, does need to know a zone identifier to reliably send data to a link-local address. ("In general", since there should(4007) be a default zone, but an RD may easily have multiple interfaces). The expectation there is that whenever it receives a link-local address, it will use that address on the interface on which it received it from. (So in a way there's still zone identifiers, they're just never written on the wire because one can only "talk" about link-local addresses on the link they apply to). 
> 
> So if the scenario we think about where a CT enters LL addresses into an RD is that the CT is on the same link as the endpoints, all is fine and
> 
> If Base URI contains a link-local IP literal, it MUST NOT contain a Zone Identifier,
> and MUST be local to the link on which the registration request is received.
> 
> can stay, all is fine, and CTs can _only_ enter LL addresses if they are on the same link. 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/core-wg/resource-directory/issues/165#issuecomment-449432358
[2]

**Comment by chrysn** [comment]
Sounds we're good on that point. @cabo, are you happy with the semantics of bdfecd17c161f3b45f85dfce30125c8c24c4b0b3?

(I've spotted some wording quirks to be fixed, but would like to confirm that the meaning is agreeable.)

**Comment by chrysn** [comment]
With cabo's changes in c8a0fec79acd5 (which also fix the mentioned quirks), that should be it.

I've been thinking of adding a paragraph of implementation advice saying that whichever RD implementation doesn't want to bother with this is free to just not run on link-local interfaces (by not binding there, by making their `[fe80::...]/.well-known/core` empty or by having it show full URIs with a routable address of themselves), but that probably doesn't belong in the text.

Please re-open if you think I'm wrongly closing this now.
