### ISSUE TITLE
Delete extra-attributes

### ISSUE THREAD

**Issue by jimsch** [core-wg/resource-directory#187]
It may be worth while to add a sentence in the registration updating section that if an attribute is to be deleted then the registration needs to be replaced rather than updated.

**Comment by chrysn** [comment]
That'd be a

    Endpoint attributes without explicit processing can only be changed by updates,
    not removed completely. Currently, the only way to remove them is to replace the
    whole registration by performing the Registration step again.

paragraph in the update's extra-attrs.

I'd be weakly against adding this as it follows from there not being any other way described, but if anyone else +1's it, I'll merge it in.

**Comment by petervanderstok** [comment]
+-0

Peter
chrysn schreef op 2018-12-21 15:41:

> That'd be a
> 
> Endpoint attributes without explicit processing can only be changed by updates,
> not removed completely. Currently, the only way to remove them is to replace the
> whole registration by performing the Registration step again.
> 
> paragraph in the update's extra-attrs. 
> 
> I'd be weakly against adding this as it follows from there not being any other way described, but if anyone else +1's it, I'll merge it in. 
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/core-wg/resource-directory/issues/187#issuecomment-449405480
[2]

**Comment by jimsch** [comment]
I don't agree that it is implicit - I kept trying to jigger a way to mark things as deleted, but I would not die on this hill.

**Comment by jaimejim** [comment]
Would it be OK to mark this issue as done or "can't fix"?

**Comment by chrysn** [comment]
That depends on what still works procedurally. I had this as "yeah could do that but nobody cares much" up until jim's latest comment. It's not hard to fix, it's just another paragraph to get OK'd. Could be fixed easily by adding (after "Otherwise, unknown attributes are stored as endpoint attributes, overriding any previously stored endpoint attributes of the same key.") a paragraph:

> Note that this default behavior does not allow removing an endpoint attribute in an update. For attributes whose functionality depends on the endpoints' ability to remove them in an update, it can make sense to define a value whose presence is equivalent to the absence of a value. 𝄌 As an alternative, an extension can define different updating rules for their attributes. That necessitates either discovery of whether the RD is aware of that extension, or tolerance the default behavior.

(Where the text after the 𝄌 can be left off without any ill effect).

@jaimejim, is this a kind of change that can still be done in the document's current stage?

**Comment by jimsch** [comment]
If it does not get fixed it is not a horrid issue.   What ever.

**Comment by jaimejim** [comment]
We are close to the cutoff, I wonder if Christian could do a last update to reflect Jim's comments. 
For example the paragraph above looks good to me.

**Comment by chrysn** [comment]
Included in -23 as per chat following the latest comments.
