### ISSUE TITLE
Item categories for interactions

### ISSUE THREAD

**Issue by cabo** [core-wg/resource-directory#191]
The entries for "Failure" are quite repetitive for 4.00 and 5.03.  Can we factor these out a bit?

The entry "HTTP support" is surprising; maybe this item should be explained beforehand.  (It seems all it is saying is that HTTP does not do multicast or /.well-known/core?)

(via Jaime)

**Comment by chrysn** [comment]
@mjkoster and @petervanderstok, AFAIR both of you argued for the interaction templates in the length they have now, but I failed to find the old arguments. (There were some unresolved points in #6 and #116 and #127, but they don't tell the whole story).

I'd argue that most of the failure codes can be removed, for they can't be exhaustive anyway (would we need to add 4.01 for when the client would need to authenticate? 4.08 if a block was missed? 4.29 to throttle?) – handling those is part of CoAP and not the application.

If I were to make a proposal, I'd replace all "Failure:" paragraphs (except 4.04 on update/removal, as that's particularly noteworthy) with a general note that

> REST clients (registrant-EPs / CTs, lookup clients, RD servers during simple registrations) MUST be prepared to receive any unsuccessful code and act upon it according to its definition, options and/or payload to the best of their capabilities, falling back to failing the operation if recovery is not possible. In particular, they should retry the request upon 5.03 (Service Unavailable; 503 in HTTP) according to the Max-Age (Retry-After in HTTP) option, and fall back to link-format when receiving 4.15 (Unsupported Content Format; 415 in HTTP).

Are the sections still justified to be that long, and if so, could you contribute a note on why that is for the review of [Jaime's comments](https://mailarchive.ietf.org/arch/msg/core/vt7JiBeAI6XrkpKI1UWMbnMc9B8)?

**Comment by chrysn** [comment]
A point I missed that should go after that suggested paragraph, to fully cover Jaime's comment:

> All operations are conceptually supported on CoAP and HTTP. Multicast discovery operations are not possible on HTTP, and Simple Registration can not be executed as base attribute (which is mandatory for HTTP) can not be used there.

**Comment by petervanderstok** [comment]
I have made no contribution to template length or format. I don't remeber arguments that support their length. Having written that, I like to idea of having templates. I like them to be stand-alone which makes them lengthy. I have enormous problems with the response codes. Their text never covers what you want to express, they remain approximations of the problem unless they are at the general server level. My sugesstion is not change what is there, but I will not oppose the general text although I consider it possibly too vague for standardization.
