### ISSUE TITLE
"NAT gateway": precision

### ISSUE THREAD

**Issue by chrysn** [core-wg/resource-directory#192]
The current text says "behind a NAT gateway" as one case in which `base` is obligatory. Reviewing [Jaime's comments](https://mailarchive.ietf.org/arch/msg/core/vt7JiBeAI6XrkpKI1UWMbnMc9B8) (esp. the part on making base mandatory all the time) I noticed that this should probably be made more precise (would have said "NAT other than full cone", but RFC 4787 has better terminology I'll yet need to go through).

**Comment by petervanderstok** [comment]
other than full cone?

**Comment by chrysn** [comment]
"Full cone" is an older term that AFAICT roughly means that for each inside port there's an outside port as well (a rather uncommon setup at least in the simple setups I've seen), but anyway that's neither the modern term nor the right criterion.

The criterion is probably "If a registrant-ep residing on the internal side NAT that does not follow the recommendations of {{?RFC4787}} with no stringent filtering (in particular REQ-1 and the Endpoint-Independent Filtering of REQ-8) registers with a Resource Directory on its external side, it MUST NOT register with the RD unless it gives an explicit base address that is usable for the lifetime of the registration (e.g. using a configured forwarded port)."

I've left the general requirement structure as it is, ie. from the normative language, the registrant has to know about the network. This is unreasonable to demand of the software implementation, and will need to be covered by the implementation's usage instructions or similar (a la "If you deploy this in behind a NAT, you have to add port forwarding and give the externally visible address in this configuration field (which becomes base), otherwise your endpoint would not be compliant") – but that does not change with this edit, and I still think it's good that way.

Reading 4787 I also noted that the lifetime interacts with this as well; in the same vein as "if in a really-bad NAT then set base", there'd be a "if in a regular NAT, need to refresh often enough"; not sure which line that'd go into yet.

**Comment by petervanderstok** [comment]
I would be carefull with any of these instructions because they arre
very general and new boxes between communicating nodes may appear any
time.
chrysn schreef op 2019-03-05 17:16:

> "Full cone" is an older term that AFAICT roughly means that for each inside port there's an outside port as well (a rather uncommon setup at least in the simple setups I've seen), but anyway that's neither the modern term nor the right criterion. 
> 
> The criterion is probably "If a registrant-ep residing on the internal side NAT that does not follow the recommendations of {{?RFC4787}} with no stringent filtering (in particular REQ-1 and the Endpoint-Independent Filtering of REQ-8) registers with a Resource Directory on its external side, it MUST NOT register with the RD unless it gives an explicit base address that is usable for the lifetime of the registration (e.g. using a configured forwarded port)." 
> 
> I've left the general requirement structure as it is, ie. from the normative language, the registrant has to know about the network. This is unreasonable to demand of the software implementation, and will need to be covered by the implementation's usage instructions or similar (a la "If you deploy this in behind a NAT, you have to add port forwarding and give the externally visible address in this configuration field (which becomes base), otherwise your endpoint would not be compliant") - but that does not change with this edit, and I still think it's good that way. 
> 
> Reading 4787 I also noted that the lifetime interacts with this as well; in the same vein as "if in a really-bad NAT then set base", there'd be a "if in a regular NAT, need to refresh often enough"; not sure which line that'd go into yet. 
> 
> --
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/core-wg/resource-directory/issues/192#issuecomment-469742116
[2]

**Comment by chrysn** [comment]
Valid point; so can we put that more generally? Maybe

> A registrant that can not be reached by potential lookup clients at the address it registers from (e.g. because it is behind some form of Network Address Translation (NAT)) with MUST provide a reachable base address with its registration.

? Adding "or uses an ephemeral port to register" to the parentheses would even allow this to swallow the paragraph before as well.

(Nitpickers might argue that this needs an exception for link-local addresses, but we're talking about them in the next paragraph).
