### ISSUE TITLE
M2M vs IoT

### ISSUE THREAD

**Issue by chrysn** [core-wg/resource-directory#194]
From [Jaime's review](https://mailarchive.ietf.org/arch/msg/core/vt7JiBeAI6XrkpKI1UWMbnMc9B8):

> p3 p12 - I think we could move on and update the term "machine-to-machine" to "Internet of Things" throughout the document, unless there is a specific need to keep M2M still there.

If we want to change that, the M2M (machine to machine) references would largely be replaced with IoT (Internet of Things) in abstract, introduction and use cases (LWM2M obviously unaffected), where "new users: machines" could be replaced with "new users: devices without physical operator interaction".

@mjkoster, you wrote those texts and are probably more up to date with widespread terminology than I am – keep or change?

**Comment by petervanderstok** [comment]
I don't care too much about this terminology. IoT or LWM2M are used to address a market segment. From that point of view we need to keep them both,
