### ISSUE TITLE
One more shifting of heading levels

### ISSUE THREAD

**Issue by chrysn** [core-wg/resource-directory#195]
[Prompted by Jaime](https://mailarchive.ietf.org/arch/msg/core/vt7JiBeAI6XrkpKI1UWMbnMc9B8):

> p33 - As per the document structure, there are two interfaces: registration and lookup. Shouldn't they be at the same level in the document? Registration is 5.3, shouldn't lookup be 5.5 instead of 6?

He has a point; if we're to change that, it could be

    4. General operation
      (would get the general text of what was 5. Resource Directory)
      4.1 (was 4)  Finding a Resource Directory
        ..  Resource Directory Address Option (RDAO)
      4.2 (was 5.1)  Payload Content Formats
      4.3 (was 5.2)  URI Discovery
    5. (was 5.3.)  Registration
      5.1 (was 5.3.1) Simple Registration
      5.2 (was 5.3.2)  Third-party registration
      5.3 (was 5.4)  Operations on the Registration Resource
        ..  Registration Update
        ..  Registration Removal
        ..  Further operations
    6. (as it was)  RD Lookup
      ..  Resource lookup
      ..  Lookup filtering
      ..  Resource lookup examples

Yay or nay?

**Comment by petervanderstok** [comment]
Puts lookup and regitration at same level. That is good.
Title of 4 : It is a bit of a hodge-podge, RD discovery and syntax?
