### ISSUE TITLE
Say something about how limited devices can be

### ISSUE THREAD

**Issue by chrysn** [core-wg/resource-directory#197]
From [Jaime's review](https://mailarchive.ietf.org/arch/msg/core/vt7JiBeAI6XrkpKI1UWMbnMc9B8), again:

> p3 - "with limited RAM and ROM" Adding a reference to the expected RAM
> and ROM would be good. https://ieeexplore.ieee.org/document/6970748/
> provides an estimation of <2kB of minimum RAM and <30kB of minimum ROM
> for common IoT OSs.

That's not trivial to answer, given an RD endpoint should reuse much of existing CoAP infrastructure on a device.

I'm looking through the RIOT example, but that's not particularly optimized and carries a command-line tool to manage the registration in a build that uses ~80k ROM and ~25k RAM, but that's largely package buffers (which are reasonably sized for additional applications but not required for the RD; RD itself consumes about 150 bytes RAM plus unknown on stack) and probably 1k of ROM from the RD application – I can try to refine those numbers, but anything more optimized would be better to look at.

Does anyone have numbers on how constrained an RD client can be?

**Comment by chrysn** [comment]
I've drilled down a bit more on the RIOT examples' numbers:
* The full registration example attributes 1.7k of ROM and 1.8k of RAM to the endpoint (RIOT 6886ca54, examples/cord_ep; `make BOARD=firefly`; `size bin/firefly/cord_{common,ep}.a -t`), whereof 1k RAM is default stack size that's barely used AFAICT. I'd be confident to claim that full registration "can be implemented using less than 2k of ROM and 1k of RAM on Class 1 devices if the rest of CoAP stack is in place".
* I didn't try to get numbers for simple as the RIOT implementation is still comparatively flexible. A minimal implementation would be more taxing in terms of timer slots (one) and messages-exchanged (2-4 more per interval) than on the simpler metrics of constrainedness (I'd say +100B ROM and no RAM but the timer), but that'd depend so much on the rest of the application that numbers really make no sense.

Looking for where to best put that in, I found that the sentence in question is probably 1:1 from RFC7959 (blockwise) and just has not been updated to reference RFC7228 CoRE Terminology. That paragraph has become shorter over the WG's publication history.

Im proposing a change to that paragraph that reflects the current state (things *have been* established since this draft was started) and give a concrete reference to constrained devices (RFC7228) without going into details on what's small (follow the link for that).

IMO PR #202 is sufficient to sketch "constrained" in this context; actually giving numbers would rather open up discussions about how good they are and what else is better, and the ones I've pulled out above are ballpark level only and not published "We've done X in Y bytes" level.

@jaimejim, would you consider your concerns addressed with #202?

**Comment by petervanderstok** [comment]
The issue of how constrained devices can be, will fluctuate with time, technology and technology prices.
I am usually amazed about what people consider as vital to introduce into the code; for example: database processing with synchronized backups. So no comment from me in general.
Considering the RD. In my view, this will reside in the border router. Routers usually are fully equipped with all memory you need. I have seen proposals where the RD is separated from the registered devices by at least a border router. Think of an industrial PC.

**Comment by chrysn** [comment]
Apart from the general matter of people building kitchen sinks, would you accept the text of (what is now) #203?

I'd classify it as editorial-only as it mainly puts a reference where before it said 8-bit microcontrollers, and says that CoRE has done rather than plans to do, but it's prominent enough in the document I'd prefer not to merge it w/o anyone else's Go.

**Comment by jaimejim** [comment]
@chrysn as far as I'm concerned the new changes look good to me, as they give some precision on a minimal implementation. If it is ok I will close the item.
