### ISSUE TITLE
IANA considerations language

### ISSUE THREAD

**Issue by cabo** [core-wg/resource-directory#215]
Where IANA has not yet allocated a value, we cannot say "has allocated a value".  Yes, it is a bit tedious to change this once the allocation has been done, but IANA has to be able to derive from the text what it needs to do.

Also, I don't understand the "equal to" language in section mc-registration; do you mean ", the same as"?

**Comment by chrysn** [comment]
Changing this as of finishing up the pending comments.

Ad "equal to", my understanding is that we don't actually register a new address but just ask people to use "All CoAP nodes" for the same purpose (given the tighter address space). Is that the agreed-upon intention? If so: Does this warrant IANA action (by adding another name alias to the same address), or won't we just say where we use it that there ain't no IPv4 multicast address for that, and All CoAP nodes are used instead?

**Comment by cabo** [comment]
> On Jul 2, 2019, at 10:58, chrysn <notifications@github.com> wrote:
> 
> Changing this as of finishing up the pending comments.
> 
> Ad “equal to", my understanding is that we don't actually register a new address but just ask people to use "All CoAP nodes" for the same purpose (given the tighter address space).

I cannot recall a recent discussion on this, but this is indeed one possible interpretation of the not so clear language.

> Is that the agreed-upon intention? If so: Does this warrant IANA action (by adding another name alias to the same address), or won’t we just say where we use it that there ain't no IPv4 multicast address for that, and All CoAP nodes are used instead?

I don’t think the registry uses aliases.  So there would be no IANA action.
There should be no text in mc-registration (since this is for IANA), but there should be text in 4.3 URI Discovery saying that.

Alternatively, we could simply go for another IPv4 address.  The registry doesn’t seem to explode (there is just one entry after RFC 7252).  But let’s find the WG discussion first.

Grüße, Carsten
