### ISSUE TITLE
Domains as separate entities

### ISSUE THREAD

**Issue by chrysn** [core-wg/resource-directory#22]
(Summarizing a topic that came up in meetings and [on the list](https://mailarchive.ietf.org/arch/msg/core/jFjEaM0PYK72dq-i1lOLwuc9To4))

Based on the notion of the domains managed in an RD being fully independent of each other "like ships that pass in the night", the idea has been brought up to do away with the domain functionality at all and have the domains exposed as different RDs by the server that would otherwise host a single RD.

Pro:

* This would align better with the general web design
* Issues with the domain lookup interface would go away (#21)
* This would be consistent with the use of RD by OCF and LWM2M, where the domains are used to separate 

Con:

* This enforces the independence of domains; setups where endpoints know their ep= but not their d= could not rely on the RD to assign them to a domain (the default domain for the given endpoint) any more.
* RD discovery would become more complicated (What would it look like at all?)
* Domains could not spring into existence any more by virtue of a device or CT registering at it
* Lookups could not span multiple domains any more

**Comment by chrysn** [comment]
(Own comment, not summarizing any more:) Note that AFAICT a classical RD could still be discoverable by the mechanisms of independent per-domain RDs. It would just need to expose itself accordingly:

`GET coap://my-rd-host/.well-known/core?rt=core.rd&d=mydomain`
`Content: </rd?d=mydomain>;rt=core.rd;d=mydomain`

(Not that I think that compatibility is an issue right now, but just to demonstrate that this is not a binary situation.)

**Comment by cabo** [comment]
The discussion unearthed that we have rather different ideas about who knows what about domains.

1.  An device not configured with a domain finding a super-RD that then tells the device its domain.  

2. A device that talks to a super-RD it discovered and then the device tells the super-RD its domain.

3. A device that knows its domain RD and its domain.

(3) is easy in the "separate RD instances" model.  (2) would need some additional functionality, but it does so in the old model as well.  (1) is a bit confusing for me because I didn't get how that works now, but it again can be easily added to separate-RD model.

**Comment by petervanderstok** [comment]
Hi Carsten,

What is a super-RD? Now I am really confused.
Cannot every RD contain links to RD eps? Nothing special about RD eps in 
my view.

A good remark was indeed ep's that do not have a domain and don't want 
one. Creating domain RDs really complicates life.

Peter

cabo schreef op 2017-05-18 18:19:

**Comment by mjkoster** [comment]
I think we have concluded that "domain" is an attribute of a registration, and applications may use as they see fit. This answers the question about domain lookups. Domain can be used as a lookup parameter or filter, but there is not a "domain lookup" and we should remove that from the lookup section.

**Comment by chrysn** [comment]
This issue has been refused in the mailing list discussions; with domain lookup gone now, though, some of the reasons for this change request have.
