### ISSUE TITLE
Example "ö" is getting swallowed by publication process

### ISSUE THREAD

**Issue by chrysn** [core-wg/resource-directory#220]
Where in our source and HTML rendering the last item in Appendix B says

     </temperature/Malmö>;rel="live-environment-data" 

that gets represented as

      "</temperature/Malmoe>;rel="live-environment-data""

in the [draft-published text version](https://tools.ietf.org/html/draft-ietf-core-resource-directory-23#section-5.3.1) (but is shown correctly in the [html version](https://tools.ietf.org/id/draft-ietf-core-resource-directory-23.html)).

I was under the impression that IDs could nowadays contain unicode characters, so maybe we just need to set a flag somewhere?

**Comment by petervanderstok** [comment]
or use Stockholm
chrysn schreef op 2019-10-25 09:35:

> Where in our source and HTML rendering the last item in Appendix B says
> 
> </temperature/Malmö>;rel="live-environment-data" 
> 
> that gets represented as
> 
> "</temperature/Malmoe>;rel="live-environment-data""
> 
> in the draft-published text version [1] (but is shown correctly in the html version [2]). 
> 
> I was under the impression that IDs could nowadays contain unicode characters, so maybe we just need to set a flag somewhere? 
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [3], or unsubscribe [4].
 

Links:
------
[1]
https://tools.ietf.org/html/draft-ietf-core-resource-directory-23#section-5.3.1
[2] https://tools.ietf.org/id/draft-ietf-core-resource-directory-23.html
[3]
https://github.com/core-wg/resource-directory/issues/220?email_source=notifications&amp;email_token=ADCZGQLWFWT3XFSDB5Q6AK3QQKOUPA5CNFSM4JE7WDPKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HUJ4ZYA
[4]

**Comment by cabo** [comment]
The July version was probably done by XML2RFC with v2 flags.
When we want to use a beyond-ASCII character in v3, this needs to be in artwork (yes. the rules are weird.  I’m trying to get them changed.)

So we cannot simply set off the examples using vspace any more; we probably need real code blocks.

Grüße, Carsten
