### ISSUE TITLE
"RD" vs "Resource Directory" vs "resource directory"

### ISSUE THREAD

**Issue by chrysn** [core-wg/resource-directory#238]
From Russ' genart review, three related points:

> General: The document uses "Resource Directory", "resource directory",
> and "RD" interchangeably.  I thin it would help the reader if just one
> spelling was used throughout.

> General: These two phrases are used:
> - Resource Directory implementations using this specification ...
> - Resource Directories implementing this specification ...
> - An implementation of this resource directory specification ...
> Please pick one, or (my preference):
> - RD implementations of this specification ...
> 
> Abstract: Some places Resource Directory is spelled out.  Other places
> RD is used.  Either spell it out just once or every time.

I'd go for "RD" throughout, with the first mentions in abstract, introduction and obviously terminology spelt out. On the phrases I'd prefer "RDs implementing this specification".

**Comment by petervanderstok** [comment]
agree with Christian's suggestion, Peter
chrysn schreef op 2020-04-15 17:25:

> From Russ' genart review, three related points:
> 
>> General: The document uses "Resource Directory", "resource directory",
>> and "RD" interchangeably. I thin it would help the reader if just one
>> spelling was used throughout.
> 
>> General: These two phrases are used: 
>> 
>> * Resource Directory implementations using this specification ...
>> * Resource Directories implementing this specification ...
>> 
>> * An implementation of this resource directory specification ...
>> Please pick one, or (my preference):     * RD implementations of this specification ...
>> 
>> Abstract: Some places Resource Directory is spelled out. Other places
>> RD is used. Either spell it out just once or every time.
> 
> I'd go for "RD" throughout, with the first mentions in abstract, introduction and obviously terminology spelt out. On the phrases I'd prefer "RDs implementing this specification". 
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
 

Links:
------
[1] https://github.com/core-wg/resource-directory/issues/238
[2]
