### ISSUE TITLE
Principles

### ISSUE THREAD

**Issue by chrysn** [core-wg/resource-directory#24]
If we agree on some basic principles RD should follow, we can phrase them into a text that both guides other decisions in the RD design and can help implementers understand the basic ideas.

As I understand, those can be

* Statements obtained from the RD should stem from statements that can be found on the origin device (on .well-known/core or other ct=40 resources linked by it).

  As of -10, this is compatible but not enforced in resource links, and absent in statements about the whole device (where registration query parameters ep, et and d are exposed as resource attributes in the endpoint lookup)

  I'd treat commissioning tools that store information on behalf of the too-constrained origin node as an exception here. Another possible exception is the RD (or something interacting with it) making more statements true, eg. by registering the nodes's address in the DNS and thus making a resolvable (and possibly more stable) name available for use in con.

* An RD registration can only be updated using the registration resource (which typically only the origin device knows).

  If some entity (eg. a DNS-SD bridge) wants to update a resource's description (eg. change an instance name or rename an endpoint), they have to find (possibly through the RD) if and where the origin server allows such modification, and put the changes there.

Are those agreeable principles, and what else belongs in that category?

**Comment by chrysn** [comment]
During the last calls, it has emerged that RD is seen as an optimization of multicast discovery on .well-known/core; this can probably be merged with the first item above.

**Comment by chrysn** [comment]
During the last calls, it has emerged that RD is seen as an optimization of multicast discovery on .well-known/core; this can probably be merged with the first item above.

**Comment by petervanderstok** [comment]
I don't see the CT as an exception; I reformulated that aspect.
