### ISSUE TITLE
Possibly incorrect definition of default of link context URI

### ISSUE THREAD

**Issue by EskoDijk** [core-wg/resource-directory#280]
Current github working draft has the text:

* A link context URI: It defines the source of the relation, e.g. *who* "hosts" something.
  In link-format serialization, it is expressed in the "anchor" attribute. It defaults to that document's URI.

This looks incorrect to me; see RFC 6690 https://tools.ietf.org/html/rfc6690#section-2.1 .
In case the target URI is absolute (so it has an origin), then rule (b) applies and the default becomes the origin of the target URI. If the target URI is relative, only then the default is taken as the base URI, i.e. origin, of the Link Format document.  But this is not "the document's URI".

New text proposed, something like:

* A link context URI: It defines the source of the relation, e.g. *who* "hosts" something.
  In link-format serialization, it is expressed in the "anchor" attribute, if present. It defaults to the origin of the link target URI (see below), if present, otherwise to the origin of the server hosting the link-format document.

**Comment by EskoDijk** [comment]
@chrysn FYI! If this needs more discussion we can also take it to the list. In case I'm wrong here, just let me know also.

**Comment by chrysn** [comment]
Fixed in 332336cb2de38a34d236334480fbb95c3b3099d9
