### ISSUE TITLE
Paragraph "From a management and maintenance perspective" unclear

### ISSUE THREAD

**Issue by EskoDijk** [core-wg/resource-directory#287]
Current master branch text is really unclear:

> From a management and maintenance perspective,
> it is necessary to identify the components that constitute the RD server.
> The identification refers to information about for example client-server incompatibilities,
> supported features, required updates and other aspects.
> The URI discovery address, as described in section 4 of {{RFC6690}} can be used to find the identification.
> 

* Does it intend to say "URI discovery process" instead of "address" ? Section 4 doesn't list such an address.
* What does it mean : "used to find the identification" ?  Can we say intead "used to identify the components" ?
* How can the URI discovery process identify client-server incompatibilities?  CoAP doesn't let you discover supported protocol versions, options, etc. as far as I know, by default.
* For those implementations not supporting I-D.bormann-t2trg-rel-impl , it is really unclear what to do with this paragraph.

**Comment by chrysn** [comment]
Oups, wrong link in the commit -- sorry for the noise

**Comment by chrysn** [comment]
The intention behind this paragraph is merely to point those who want versioning and more RD metadata that is immaterial to the regular operation to a place where they can safely do so. I see, however, how the "it is necessary to" makes this sound like more than there really is to it.

Accordingly, the incompatibilities part is not about finding that something can't work in the first place (that works on a positive-list base using rt and that like), but more for understanding later why things don't work (say, client X produces a document that upsets RD implementation Y in versions earlier than 0.4.1).

The address is in section 4 of 6690 (ie. just .well-known/core); now referred to by the name it has there.
