### ISSUE TITLE
Section 5.1: Requirement on RD depends on other network participants - hard to act on

### ISSUE THREAD

**Issue by EskoDijk** [core-wg/resource-directory#288]
> When the RD is in a position to successfully execute this second interaction and other network participants that can reach it are not,
> it SHOULD verify that

This requirement on RD seems to depend on what other network participants can achieve or not? That's something RD may not even know about.

What about this clarification:

> When the RD is authorized to successfully execute this second interaction but other network participants 
> -- that can reach the RD and/or the registrant-ep -- are not authorized to execute this interaction,
> the RD SHOULD verify that

**Comment by chrysn** [comment]
It's not only about authorization (in the sense of putting cryptographic credentials) but also about firewalls (like those described on https://en.wikipedia.org/wiki/DMZ_(computing)#DMZ_host).

The RD as a package-of-software can not know this -- it'll need to ask this at setup time or just make the conservative assumption.

The text is updated to capture both aspects and emphasize that this is about deployments.
