### ISSUE TITLE
Section 9.3.1: 'et' attribute - update scope of title; and define usage multiple times in query

### ISSUE THREAD

**Issue by EskoDijk** [core-wg/resource-directory#289]
Section 9.3.1: title suggests that 'et' is only defined in scope of being a registration (R) parameter.
However, some parts of the text also describe 'et' as being used for lookup (L) parameter or as attribute (A) in link-format descriptions for endpoint lookup results. So, the title of the section ""Endpoint Type" Registration Parameter " should be broadened to go beyond only registration (R) usage of 'et' and also include the L and A usage.

Following sentence is not fully clear what it implies for a Lookup (L) situation:

> Multiple endpoint types are given as separate query parameters or link
> attributes.
> 

For the R case it is clear -> multiple endpoint types registered. 
For the A case -> I read that a link can contain multiple 'et' attributes; this sounds ok.

For the L case, I have doubt. If I query for multiple 'et' like this
/rd-lookup-res?et=lamp&et=luminaire

will it find my device that has a single et=lamp only ? (I assume not)
will it find my device that has et=lamp and et=luminaire registered? I assume yes; using the common boolean AND of query operators for RDs.

The reason this may not be fully clear is that for other attributes (like rt, etc.) there's no definition of what to do with multiple imes the same term in a lookup query.  E.g. ?rt=a&rt=b will always return the empty set.

**Comment by chrysn** [comment]
The title is being fixed, should have been RD Parameter and yes can be used RLA as in its table.

As with rd, if and any other multi-value parameter, it *can* be used multiply at lookup, and follows the same rules as all other attributes: In `?et=lamp&et=luminaire`, the terms are ANDed like all query parameters, and it matches only for devices that register both (which I expect to be rare but not impossible), just like a `;rt="a b"` can satisfy the `?rt=a&rt=b` query.
