### ISSUE TITLE
CTs, one-time-event and soft state

### ISSUE THREAD

**Issue by chrysn** [core-wg/resource-directory#290]
From Benjamin Kaduk's comments:

>    Commissioning Tool
>       Commissioning Tool (CT) is a device that assists during the
>       installation of the network by assigning values to parameters,
>       naming endpoints and groups, or adapting the installation to the
>       needs of the applications.
> 
> Is "the installation of the network" a one-time event?   (Might a CT be
> involved when adding a new device to a network at a later time?)

Is it? Paging @mcr, @petervanderstok and @EskoDijk as I honestly don't know.

Trouble is: The way CTs come across in the examples, the CT goes in, does its job and leaves. But the RD's lifetimes are finite, and "Registrations in the RD are soft state and need to be periodically refreshed". So what happens when the time runs out?

**Comment by EskoDijk** [comment]
A CT can indeed come in later to assist in a reconfiguration of the network/applications, e.g. adding a device, removing, or changing members of a group, or changing parameters of devices.

When the CT performed a registration on behalf of an IoT device the expectation is that a very long lifetime will be picked, such that the CT doesn't have to come back to refresh.
This looks problematic in case the RD state is easily lost - e.g. suppose it reboots and loses all such entries? Then there may be no CT around to send the entries to the RD again. 

(I would assume in this scenario that the CT's registration are more "permanent" so they would survive a reboot for example. Can be restored back from a database. In another project I work in the CT can perform such persistent registrations that survive reboots, using a special 'max' value of lifetime that signals persistent registration.)

**Comment by chrysn** [comment]
Thanks, with that I can at least phrase an answer to the immediate question.

Would it, in the deployments you describe, be conceivable that the CT is recalled on site on extraordinary events, like when the RD host is migrated to a different system or address?

On the reboots, I hope that we are OK with the current situation that an RD would persist its state when it can, and administrators would not use the more volatile variety when they intend to configure long lifetimes. (If we aren't, we'd need to start thinking about negotiation of lifetimes, and that'd bring a new aspect of complexity I hope to avoid).

**Comment by mcr** [comment]
chrysn <notifications@github.com> wrote:
    >> Commissioning Tool
    >> Commissioning Tool (CT) is a device that assists during the
    >> installation of the network by assigning values to parameters,
    >> naming endpoints and groups, or adapting the installation to the
    >> needs of the applications.
    >>
    >> Is "the installation of the network" a one-time event?   (Might a CT be
    >> involved when adding a new device to a network at a later time?)

    > Is it? Paging @mcr, @petervanderstok and @EskoDijk as I honestly don't know.

    > Trouble is: The way CTs come across in the examples, the CT goes in,
    > does its job and leaves. But the RD's lifetimes are finite, and
    > "Registrations in the RD are soft state and need to be periodically
    > refreshed". So what happens when the time runs out?

Hi.
I thought I had commented on this somewhere already.
* A BRSKI-based "CT" would have a registrar which does not really leave.

* If we are talking about how *I* think that brski-async-enroll will work,
  then the CT will enter the no-internet-zone, do some connections, and
  then leave.  (Think new home construction in a new suburb)
  The RD lifetimes could be finite, but a few years in duration.
  The home owner, upon getting the *keys* (physically and cryptographically),
  would of course, *rekey* the entire house, and now there would be a
  management system to update RD lifetimes.

* Thread has a CT.  I have no idea how it works, but perhaps @EskoDijk could comment.

* Zigbee CHIP project is doing something, but it's all NDA for now.

I think that, when the time runs out, if there is nothing else to manage the
system, then it should fail.  I think that's okay.  I think that the
timeouts won't be minutes, but months... yes, there are issues.
I don't think that the RD document needs to cover them though.
{Feel free to invite me to collaborate on a script for the sequel to
Sneakers/Leverage/MissionImpossible/EnemyOfTheState.  I suggest it star Tom
Greene rather than WillSmith or TomCruise.}

**Comment by mcr** [comment]
> Thanks, with that I can at least phrase an answer to the immediate question.
> 
> Would it, in the deployments you describe, be conceivable that the CT is recalled on site on extraordinary events, like when the RD host is migrated to a different system or address?

I think that there is probably a followup document that provides a way to backup/restore RD host data.
OPC UA told me that they have created a spec for device independent backup/restore of configuration data in the case of device failure, but I don't have the details yet.

**Comment by chrysn** [comment]
> I think that there is probably a followup document that provides a way to backup/restore RD host data.

This might fit into [rd-replication](https://tools.ietf.org/html/draft-amsuess-core-rd-replication-02) -- any exchange format between the RDs could also be re-used for persistence. (With the caveat that the receiving server would need to inhabit the same address as the original server, or otherwise it could not service registration updates.)

**Comment by mcr** [comment]
> > I think that there is probably a followup document that provides a way to backup/restore RD host data.
> 
> This might fit into [rd-replication](https://tools.ietf.org/html/draft-amsuess-core-rd-replication-02) -- any exchange format between the RDs could also be re-used for persistence. (With the caveat that the receiving server would need to inhabit the same address as the original server, or otherwise it could not service registration updates.)

Well, could it be an anycast address so that the RD could be highly available?

**Comment by EskoDijk** [comment]
> Would it, in the deployments you describe, be conceivable that the CT is recalled on site on extraordinary 
> events, like when the RD host is migrated to a different system or address?

I don't see this as a viable design for a deployment. A change of system/address/network in the backend should never require the CT to come in and redo commissioning operations on IoT devices. Feeding the 'new RD' with stored information from a database is what would be most useful here. This database could be all those entries of devices that the CT had scanned initially, not necessarily the full RD state. Or alternatively all RD entries with lifetime e.g. > 48 hours could be restored; other devices need to re-register.  Those entries that were registered with the CT could have a 10-year lifetime for example.

**Comment by petervanderstok** [comment]
HI all,

There are many installation firms, all with their own procedures and
tools.
It is possible that an installation company deploys a CT during
installation and takes it home afterwards. The contract might stipulate
that he leaves behind a program to restart, update or refresh the
network. It might be that an another company does the maintenance with
another set of tools.

Concerning duration,  we may talk about years of operation  without
interruption. On other sites weekly upgrades may be necessary.

At the end of the day, There are no general rules that may fix the CT
behavior.

I am afraid this does not help a lot and emphasizes that the CT example
is just a likely example.

Cheerio,

Peter

Esko Dijk schreef op 2020-10-21 09:02:

>> Would it, in the deployments you describe, be conceivable that the CT is recalled on site on extraordinary
>> events, like when the RD host is migrated to a different system or address?
> 
> I don't see this as a viable design for a deployment. A change of system/address/network in the backend should never require the CT to come in and redo commissioning operations on IoT devices. Feeding the 'new RD' with stored information from a database is what would be most useful here. This database could be all those entries of devices that the CT had scanned initially, not necessarily the full RD state. Or alternatively all RD entries with lifetime e.g. > 48 hours could be restored; other devices need to re-register. Those entries that were registered with the CT could have a 10-year lifetime for example. 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
 

Links:
------
[1]
https://github.com/core-wg/resource-directory/issues/290#issuecomment-713355722
[2]
