### ISSUE TITLE
Some example coap:// URIs that use port 5684

### ISSUE THREAD

**Issue by EskoDijk** [core-wg/resource-directory#293]
Looking in the master branch .md doc: some examples use a coap:// URI (not secure) that use the port 5684, which is normally reserved for coaps:// (secure).  Better use other port numbers for these examples, e.g. ones in the dynamic range, or currently unallocated ones?

**Comment by chrysn** [comment]
I think for the next I-D I'll be doing examples in, I'll just write a script that sets up the examples in an implementation and sniffs out the examples content.

Thanks for spotting yet another case of example inconsistency. (Those should be using coaps as that's what the base URI is updated to).
