### ISSUE TITLE
Risk of concurrent query-result-set update when using page/count query attributes?

### ISSUE THREAD

**Issue by EskoDijk** [core-wg/resource-directory#314]
The rd-lookup client may use page/count query attributes to paginate the result. However, in the time between requesting two "pages" the result set may have changed already meanwhile, leading to potentially missing items or duplicated items in the two pages requested. Is there something the client can do here e.g. if the RD server includes an ETag and the client does conditional GETs with an If-Match Option on that tag value?  This should (hopefully) ensure that all pages come from the same resource representation. If the GET for a page thus fails, the client could go back to fetching page 1 again if it wishes to have a truly consistent representation.

Alternative to mentioning a mitigation technique like ETags is just warning that such inconsistencies may happen.

**Comment by chrysn** [comment]
I don't see much potential for ETag to protect paginated results for two reasons:
* It'd be digging pretty deep into something we otherwise don't make rules about and may thus be hard to implement (for example, some servers generate ETags at blockwise time from the full body's representation), and
* it's not much use: A client that fetches paginated results and starts over at a change could just as well have used unpaginated block-wise from the start. (Yes losing the ability to seek ahead, but what would that mean with unsorted results).

Thus I'll go with the suggested alternative and outline the issues.

(Frankly, if it were for me personally, pagination would be out without replacement; WG was in favor of keeping this despite its shortcomings when it was discussed dunno-when ago.)

**Comment by petervanderstok** [comment]
Yep, to my great grief as well.

chrysn schreef op 2021-02-22 11:03:

> I don't see much potential for ETag to protect paginated results for two reasons: 
> 
> * It'd be digging pretty deep into something we otherwise don't make rules about and may thus be hard to implement (for example, some servers generate ETags at blockwise time from the full body's representation), and
> * it's not much use: A client that fetches paginated results and starts over at a change could just as well have used unpaginated block-wise from the start. (Yes losing the ability to seek ahead, but what would that mean with unsorted results).
> 
> Thus I'll go with the suggested alternative and outline the issues. 
> 
> (Frankly, if it were for me personally, pagination would be out without replacement; WG was in favor of keeping this despite its shortcomings when it was discussed dunno-when ago.) 
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
 

Links:
------
[1]
https://github.com/core-wg/resource-directory/issues/314#issuecomment-783254117
[2]

**Comment by cabo** [comment]
The Etag would be for the subset requested by the pagination selectors anyway.
We need something that is more useful for saying "OK, I have frozen the state for a while so you can make paginated/block-wise requests for that frozen state".

**Comment by cabo** [comment]
Obvious, the freezing would need to be best-effort, or it becomes a DoS target quickly.

**Comment by chrysn** [comment]
We already have this best-effort freezing in RFC7959 ("To minimize the
   resulting inefficiency, the server MAY cache the current value of a
   representation for an ongoing sequence of requests.  (The server may
   identify the sequence by the combination of the requesting endpoint
   and the URI being the same in each block-wise request.)").

I see pagination as it is as a way for a client to get usable-but-not-perfect results from a server that is conservative in its freezing on the block-wise side (ie. invalidates ongoing block-wise transfers all the time).

I'm game for more complex schemes that are useful while neither freezing (that could be done with block-wise too) nor being racy. There are probably even existing good examples of how to do this, like all these cursor-based things. But spec'ing them out here would be beyond scope.

**Comment by cabo** [comment]
Yes, maybe we need a pagination document (that could include such features for block-wise).  Not here, indeed.
