### ISSUE TITLE
Clarify text in 3.1

### ISSUE THREAD

**Issue by jaimejim** [core-wg/resource-directory#32]
There is text in section 3.1 “Principles” of the RD draft that says…
 
   …snip…”it follows that no information should be stored in the
   resource directory that cannot be discovered from querying the
   described device's /.well-known/core resource directly.”
 
This seems counter to the text in section 1 “Introduction”, which says…
 
…snip…”These problems can be solved by employing an
   entity called a Resource Directory (RD), which hosts descriptions of
   resources held on other servers, allowing lookups to be performed for
   those resources.”
 
Could the text in 3.1 be re-stated differently?

**Comment by chrysn** [comment]
I'm note sure see the conflict; is it the "hosts", which could be read as being authority on and could be replaced with "mirrors"? Or is it more about the query interfaces that are not present on the original devices?

**Comment by chrysn** [comment]
> I'm note sure see the conflict; is it the "hosts", which could be read as being authority on and could be replaced with "mirrors"? Or is it more about the query interfaces that are not present on the original devices?

@jaimejim, could you elaborate on that? I do not understand the conflict.

**Comment by jaimejim** [comment]
To be honest I am not sure what the issue was. I think that in a first read it gave the impression that the RD was the host of the resources instead of mirroring them. I'll close it.
