### ISSUE TITLE
Clarify processing of lifetime with new registration of already registered device

### ISSUE THREAD

**Issue by boaks** [core-wg/resource-directory#33]
According 

https://github.com/core-wg/resource-directory/blob/master/draft-ietf-core-resource-directory.md#registration-registration

> A new registration may be created at any time to supersede an existing registration, replacing the registration parameters and links.

and below

> lt := : Lifetime (optional). Lifetime of the registration in seconds. Range of 60-4294967295. If no lifetime is included in the initial registration, a default value of 86400 (24 hours) SHOULD be assumed. If the lt parameter is not included in a registration refresh or update operation, the most recently supplied value SHALL be re-used.

Therefore I'm not sure, if the explanation for the `lt` about the reuse of the most recently supplied value, just doesn't apply here (and may be moved to a more proper place), because this section is only about **new** or **replacing** registrations, or, if **refresh** or **update** registrations also apply to this section, somehow "extends" the behaviour of "replacing the registration parameters and links" (and may be therefore explicitly mentioned as exception in the "replacing the registration parameters and links, except the lifetime, where the below extra rule SHOULD be applied").

FMPOV, I don't see the use case, where a device sends a registration and the rd should use a previous lifetime without notice the device about that. The device would consider the default value, but, if the actual value would be smaller, the device will get unaware unregistered.

An example for "supersede" case would therefore be also a good idea, to clarify, what is intended.

**Comment by mjkoster** [comment]
Hi Achim,

I agree, we should remove the text about refresh from the description of new registrations, and it wil remove the confusion.

Thanks!

Michael

**Comment by chrysn** [comment]
I agree: if a device re-registers by POSTing to the RD (rather than to its registration resource), it can often be the case that it has lost knowledge of its previous registration, so carrying defaults over from that would lead to misunderstandings.

No other variables in the same section are affected by this issue.

Pull-request with updated wording is pending; will merge it if no objections are brought up.

**Comment by boaks** [comment]
Thanks!
