### ISSUE TITLE
more con context

### ISSUE THREAD

**Issue by petervanderstok** [core-wg/resource-directory#40]
Hi Jim,

Indeed, the text 5.3.4 can confuse people.
We have added an entity-relationship model to he draft that shows that context is an attribute of the registration.
Currently, all links of the registration resource share the same context.
Citing the context when comparing links in the same registration resource is superfluous.
I think that 5.3.1 should read about all links over all registration resources within an RD.

Text will be modified.

Thanks for pointing this out.

Peter

Jim Schaad schreef op 2017-08-31 06:55:
In reading through and working on implementing this draft, I have found what
appears to me to be conflicting language on the context parameter.

Section 5.3.4 indicates that context + target could have collisions and that
this is likely to occur if there are multiple configuration tools.  This
text appears to me to indicate that the context can be different for each
link in a registration resource.  Each update could provide a different
context.  (I will note that the text probably needs to discuss dealing with
both normalization of the context and building the full URI from the context
and target when doing the comparison.  The pairs
<coap://ep.example.com:5683, /foo/bar> and  <coap://ep.example.com/foo,
/bar> should probably compare as identical.

Section 5.4.1 in the third paragraph talks about updating the lifetime and
context in the same paragraph  Since I know that the lifetime is a parameter
of the registration resource, it is reasonable from the context to assume
that the context would also be a parameter of the registration resource
rather than of a link.

In my opinion, these are conflicting concepts of what the meaning of context
is.  Would it be possible to figure out which is supposed to be correct and
both let me know and update the document?

Jim

**Comment by mjkoster** [comment]
The purpose of "con" is to allow explicit control of the scheme and authority (and also base path for e.g. a bridge or gateway) of a registration, or when an ephemeral port is used in the client stack to do the registration. Without con, the RD would only be able to infer the scheme and authority from the client network information.

There was never an intention to have a context per link; that is what "anchor" is for.

Resource lookups will return links using "con" as the scheme, authority, and base path if provided. If not, resource lookups will return the scheme and authority derived from the registering client.

**Comment by petervanderstok** [comment]
I still think that adding base path in con= is confusing.
Question: why can the hosts relation not change the base path?

As Chris remarks, restricting con the authority and scheme, provides the possibility to return multiple authorities and schemes with as many con= values.

**Comment by mjkoster** [comment]
Please see my other comment about "hosts". We could use "anchor" in links to set the context on registration, and remove "con" entirely if "con" can not easily be explained or understood..

**Comment by chrysn** [comment]
The plurality of links section (5.4.3) is one I don't really understand either.

Given that the registration is supposed to be idempotent, how can that situation occur in the first place?

**Comment by chrysn** [comment]
I think that this issue refers to content that has been updated in the meantime and is not that confusing any more, please confirm by closing the issue.
