### ISSUE TITLE
ER: modelling link-format serialization vs. modelling semantics

### ISSUE THREAD

**Issue by chrysn** [core-wg/resource-directory#54]
Working with the ER model of `.well-known/core` in preparation of explanations around the use of anchor and href, I noticed that the model is something between a model of the link-format serializations and the web links data model.

It uses much of the serialization's terminology ("anchor" and "href"), and refers to some cardinalities as they appear in the serialization (eg. anchor is 0-1 because it may be omitted), but at other places alludes to the data model (eg. rel has cardinality 0+, which reflects that a link can have several relations, but in the serialization they all get space-joint into 0-1 rel parameters).

The model is now much closer to the serialization than the semantic model, and I think we should stay with that to keep the document from becoming too abstract. (Plus, I don't know which applications start breaking when we make `</a>;rel=x;foo=bar,</a>;rel=y;foo=baz` into `</a>;rel="x y";foo=bar;foo=baz` which we could when we say the RD's data model is the abstract web linking model).

Are we OK with the model reflecting the serialization and not the semantics?

If if should reflect the serialization, the only discrepancies I spotted are that cardinality of rel and con are 0-1 (that count being low is probably another hint that it should stay this way).

**Comment by petervanderstok** [comment]
Hi Chris,

Personally, I prefer the semantic model.
The serialization is a different issue. I can imagine documents which 
improve the current serialization documents on JSON, CBOR and 
link-format; and that would mean changing the RD E-R model; which will 
not happen.

Peter

chrysn schreef op 2017-10-03 17:56:

**Comment by chrysn** [comment]
@petervanderstok do you plan on making a text suggestion until tomorrow, or shall I try to sketch one up?

**Comment by chrysn** [comment]
@petervanderstok, will you write a pull request for that until the next meeting, or shall I try to?

**Comment by petervanderstok** [comment]
@chrysn that is much work and I am out of budget for this week.; so next week is a possibility.
