### ISSUE TITLE
Action to be performed on another registeration request by the node

### ISSUE THREAD

**Issue by vyshakg30** [core-wg/resource-directory#55]
https://tools.ietf.org/html/draft-ietf-core-resource-directory-11#section-5.3

> A new registration may be created at any time to supersede
   an existing registration, replacing the registration parameters and
   links.

suppose a node sends another registeration request with any **New** core links , do we add those to its **RD** entry, as indicated by mentioning  `supersede`
Or do we **delete** the previous entry of node(resource) node from **RD** and create a **New** entry with its current payload links ?

**Comment by chrysn** [comment]
The existing links are replaced by the new ones, that means the old ones get deleted and the ones submitted are the new ones. The new registration will be in the place of the old one, and IMO group memberships will be unaffected too, but apart from that it's like delete-and-recreate.

If this does not answer your question, feel free to reopen.
