### ISSUE TITLE
"registration resource" used ambiguously

### ISSUE THREAD

**Issue by chrysn** [core-wg/resource-directory#66]
The term "registration resource" is used ambiguously in the current document:

Sometimes, it refers to the particular resource created for a single endpoint's registration (eg. `/reg/1234`). At other occasions, it refers to the resource at which endpoints can registrer (eg. `/rd`).

I'm currently out of ideas on which terms to best use, would appreciate input and post an update if I come up with anything that's not "registration endpoint" (endpoint term being otherwise using in the CoAP netloc sense)  and "endpoint location" (endpoint again, and Location because of the header that sent the client there).

**Comment by chrysn** [comment]
Seems like there are only one or two occasions where the core.rd ("`/rd`") resource is called "registration resource"; we might still want to come up with a name for that, but the relevant sentences can probably be rephrased to only refer to that resource indirectly.

**Comment by petervanderstok** [comment]
There are many places where "entry" or an other name is used to indicate 
a "registration resource"
I suggest "registration resource" with path example /rd/4521 and "RD 
resource" with path example "/rd".

When not contradicted, I will try to impose that everywhere.

Peter

chrysn schreef op 2017-10-20 15:40:
