### ISSUE TITLE
How does a client get notifications of changes to a RD?

### ISSUE THREAD

**Issue by mjkoster** [core-wg/resource-directory#7]
It would be good to provide a way for clients to receive notifications upon updates of an RD.

**Comment by chrysn** [comment]
Is this something we need to specify? IMO it'd be orthogonal to the interface description -- if the RD advertises a `</rd-lookup/ep>;obs;...`, any client can try to observe the presence of endpoints.

**Comment by cabo** [comment]
So we should just say that such a lookup can be tried with observe, and that the link attribute "obs" is a good way to provide a hint.

Any future optimized collection observe would probably use RD as a prominent example, so we can expect RD implementers to pick this up later.
