### ISSUE TITLE
Plurality should be per-registration

### ISSUE THREAD

**Issue by chrysn** [core-wg/resource-directory#70]
Granted, I don't really understand what purpose the plurality definition serves, but a clarification in https://github.com/core-wg/resource-directory/pull/69 ("... within the directory resource") brings this up:

If (as it is currently defined) plurality is checked between any two links in the whole RD, any two registrations that contain a static statement between external URIs (like the one in A.2) creates link plurality.

Such links are perfectly legal in a .well-known/core document, so why should they not be permissible in an RD?

Assigning @petervanderstok because your change triggered this, but feel free to reassign to whoever understands plurality best (I don't remember who introduced the concept).

**Comment by mjkoster** [comment]
I introduced the concept, based on a request, to deal with the idea that there may be accidentally duplicated links in an RD as an error condition.

I'm not sure it is an error to have two links exactly the same, but there may be errors that result in failure to remove old links, etc that resut in duplicates.

I think Peter was also involved; is there any other concern? Perhaps this could be removed now that we have a better understanding.

Best regards,

Michael

**Comment by chrysn** [comment]
Given that there are all kinds of permissible .well-known/core contents,
I think it's hard to describe any constraints here that correctly
indicate an implementation or usage error without precluding valid use
cases.

IMO this would be better handled at the PATCH/iPATCH-for-link-format
specification, where the more concrete measures can be taken.

The only place where what this tries to catch can happen with the
current document is at a POST to the registration resource. Would being
clear that a POST must not be considered idempotent here suffice?

**Comment by petervanderstok** [comment]
That's awkward, as elsewhere it is stated that all functions on RD MUST 
be idem-potent

Peter

chrysn schreef op 2017-10-24 15:31:

**Comment by mjkoster** [comment]
Agree to remove and deal with the potential issue in the PATCH discussion

Michael

**Comment by chrysn** [comment]
On Tue, Oct 24, 2017 at 03:49:15PM +0000, peter van der stok wrote:
> That's awkward, as elsewhere it is stated that all functions on RD MUST 
> be idem-potent

Registration is idempotent, ie. POSTing to the directory resource.

Updating a registration with new links, ie. POSTing to the registration
resource, results in plurality.

**Comment by petervanderstok** [comment]
but remains idem-potent?

That means that the same ep with identical attributes can be added an 
infinite number of times.
A note about uniqueness of ep name should take care of that problem?

Peter

chrysn schreef op 2017-10-24 18:08:

**Comment by chrysn** [comment]
> That means that the same ep with identical attributes can be added an infinite number of times.

No, adding an endpoint is registration. That's idempotent, and "keyed" to domain and endpoint name.

A `POST /rd?ep=my-node1`, done repeatedly, always returns `Created, Location: /rd/1234`, and `/rd/1234` will contain exactly once the links sent in the POST's payload, because it was and is described as idempotent.


A subsequent `POST /rd/1234, Payload: </new-res>` with additional links is the part that is affected by plurality. That is not idempotent on a REST level (because the first returns `Changed` and the second returns `Conflict: Plurality violated`), but is idempotent at application level because the plurality check keeps the link from being added.

Unfortunately, the same rules forbid simple registration of nodes whose `.well-known/core` states (in bad style, but IMO legally) `</temp>;rt="temperature",</temp>;if="core.s"`, or (which is the original topic of this issue) two registering resources from both claiming `<t123.pdf>;rel=alternate;ct=65001;anchor="http://www.example.com/sensors/t123"`. At least the latter (and I'd argue also the former) is too strict, and catches errors only at the expense of not allowing full `.well-known/core` replication any more.

**Comment by petervanderstok** [comment]
Is it OK for you, if I change text to remove parts and improve the addition problems?
I have an hour this weekend

**Comment by chrysn** [comment]
On 27 October 2017 16:43:00 CEST, peter van der stok <notifications@github.com> wrote:
>Is it OK for you, if I change text to remove parts and improve the
>addition problems?
>I have an hour this weekend

Sure, go ahead, I'll probably only continue on it on Monday.

**Comment by petervanderstok** [comment]
made new version that suppressed text on plurality of links.
conflict: when registration is creted with duplicate ep, d, values.

Addition of link in registration: Do nothing when fully identical links already exists.
