### ISSUE TITLE
Parent-from-child lookup: examples vs. text

### ISSUE THREAD

**Issue by chrysn** [core-wg/resource-directory#82]
Text and examples are currently consistent that any link parameters of the "container" (group for endpoint, endpoint for link) can transitively match a query, so `/lkp/res?et=foo` gives all resources hosted on an endpoint with et=foo.

As Michael pointed out in #35, there are inconsistencies in the reverse direction: An example shows that `/lkp/gp?ep=node1` gives groups that contain that endpoint, which is not covered by the text on lookup

It sounds sane to have an "any matches" between endpoint and group, and the same logic would allow finding the endpoint that registered a particular link ("Who said `<t123.pdf>;rel=alternate;ct=65001;anchor="http://www.example.com/sensors/t123"`?") which is useful because we don't have reification inside link-format (which I think is good because it's still for constrained devices). So we could just say that the search criterion extends in both directions, and it is sufficient to match at either a container or something contained in it.

On the other hand, from the implementation PoV, this means that all gp and ep lookups with query parameters need to traverse all registered resources. I wouldn't mind, but other implementors might.

(Even if we reach quick agreement on this, I doubt a text update for this will make it into -12 :-/ )

**Comment by chrysn** [comment]
When addressing this, we should try to make the filtering text a bit clearer, as it has sparked some questions [in a review thread](https://mailarchive.ietf.org/arch/msg/core/puP0Nv8sZnL-hW5vKQvCUvAaGRw).

**Comment by petervanderstok** [comment]
Let's try for -13; it is important enough to warrant some text

**Comment by petervanderstok** [comment]
I am not sure about the discussion.
filtering query parameters are OR'ed xor AND'ed; is this not specified somewhere?
about clarifying what should be returned by the lookup interface; That seems indeed to be too vague

**Comment by chrysn** [comment]
Re-opening as there are unaddressed phrasing issues ("a bit clearer", "review thread", "OR'ed xor AND'ed"); that will more easily be addressed when the upcoming pull request on the syntax change has been talked about.

**Comment by chrysn** [comment]
Most referenced discussions all related to an earlier version of the text; closing this.

(The only later question was @petervanderstok's on "OR'ed xor AND'ed"; ad that: "All included criteria MUST match for a link to be returned", ie. it's an AND over all query parameters.)
