### ISSUE TITLE
RD federation: group members from foreign RDs

### ISSUE THREAD

**Issue by chrysn** [core-wg/resource-directory#85]
Jim Schaad [brought this up](https://mailarchive.ietf.org/arch/msg/core/puP0Nv8sZnL-hW5vKQvCUvAaGRw):

> When creating a group registration, can the link to an endpoint be on a different resource directory?  This second RD could be either on a different machine or on the same machine (i.e. coap vs coaps).  If the answer is no, then do we need to think about some type of relation attribute in the case that multiple are listed somewhere?

**Comment by chrysn** [comment]
I like to think so (having a more distributed model in mind), but we haven't discussed it yet.

As for the specification, I think we should say that the CTs operating on the tool working on the group "SHOULD refer to the endpoint registrations either as a path-absolute relative reference (if it obtained the reference from the Location option when it conducted the registration itself), or use the reference as serialized when it obtained the location from an endpoint lookup from the same RD origin".

This leaves the door open for federating RDs (where some endpoint registrations are located at another RD host, but still available for lookup at the closest host), but discourages blind mixing of registration entities from unrelated RDs.

**Comment by petervanderstok** [comment]
The whole idea of federated RDs gives me the shivers.
What about consistency and mutual references which must be synchronized?
What about duplicates?

Another new document might be interesting, but for me it is a can of 
worms when one wants to keep things constrained.


chrysn schreef op 2017-11-02 09:48:

**Comment by petervanderstok** [comment]
can't we add an anchor to the endpoint registrations?

chrysn schreef op 2017-11-02 09:48:

**Comment by chrysn** [comment]
Yes, anchors at endpoint registrations would be a way to do it (like the results in the example in the [CoRE list thread](https://mailarchive.ietf.org/arch/msg/core/sM4C7XpcXHLvMmh76onXgB-SK84)).

So a CT might try to add group members like

    POST /rd-group
    </reg/1234>,</reg/1235>,</reg/9876>;anchor="coap://other-rd"

and the group's RD would either accept that or refuse the registration. I think that that works moderately well with the current wording "The commissioning tool SHOULD not send any target attributes with the links to the registration resources, and the resource directory SHOULD ignore any attributes that are set.", though we should consider changing the second part to "the resource directory SHOULD reject registrations that contain links with unprocessed attributes".

**Comment by petervanderstok** [comment]
Just added this possibility to my version, but the the lookup could lead to confusion.
There is an anchor for the ep resource and a con for the multicast address.

**Comment by chrysn** [comment]
Just merged it because it's good to have the text there, but I'd tone it down to be clear that we don't expect RDs to just accept EPs from any other RD.

As the anchor and href details need to be overhauled with the results of yesterday's meeting, I'll suggest modifications for that after the absolute URI change is through.

**Comment by petervanderstok** [comment]
I have added text after group example in section 6.1 to clarify the existence of an absolute URI.
In section 7.4 the group lookup example is changed from relative URI to absolute URI (similar to resources) with maintenance of anchor attribute (although I doubt its utility).

This issue can be closed for me after acceptance of pull request

**Comment by chrysn** [comment]
After the 2017-01-25 meeting, I wrote the considerations for replicated or federated RDs into a dedicated document to get the issues out of the way here. (Otherwise, we'd either have to specify some federation here to justify examples with foreign registrations in groups, or leave it out at all and limit the possibilities for extension). The resulting document is [draft-amsuess-core-rd-replication-00](https://tools.ietf.org/html/draft-amsuess-core-rd-replication-00).

The mechanisms and scenarios described there indicate (in Section 5) that there are some points where the RD could assist a more distributed operation with small changes:

*  Explicitly allow "foreign" URIs in discovery and endpoint lookup (Group lookups have this in examples, other places don't even allow it)
*  Say something about what to do on registration or renewal failure: When should discovery be restarted?
* Allow empty submissions

I'm tracking those items in this bug as I don't expect them to be very controversial, pull request is coming up.
