### ISSUE TITLE
Registration expiry and group membership

### ISSUE THREAD

**Issue by chrysn** [core-wg/resource-directory#86]
We are explicit about Registration Removal ending group membership, but do not say the same about the eventual deregistration from a timeout (only "The RD MAY eventually remove the registration resource for the purpose of resource recovery and garbage collection.  If the Registration Resource is removed, the endpoint will need to re-register.")

A simple "[garbage collection], and remove it from any group it belongs to." would IMO suffice.

**Comment by petervanderstok** [comment]
looks reasonable.

chrysn schreef op 2017-11-02 09:56:

**Comment by petervanderstok** [comment]
done in my version
