### ISSUE TITLE
Multicast heuristic: use "All CoAP Nodes"

### ISSUE THREAD

**Issue by chrysn** [core-wg/resource-directory#87]
The -12 draft suggests as a heuristic to ask at `coap://[ff02::1]/.well-known/core?rt=core.rd*`.

There is a multicast address for All CoAP Nodes, I suggest we use that (would be `coap://[ff02::fd]/...`).

**Comment by cabo** [comment]
Indeed, that is an obvious change to be made.  

We also could think of registering a multicast address for "all CoRE resource directories", if that turns out to be useful.

**Comment by petervanderstok** [comment]
agree fully with Carsten

chrysn schreef op 2017-11-04 13:07:

**Comment by chrysn** [comment]
I like the "All CoRE RDs" address. It's trivial for IPv6, but the v4 addresses are more scarce. Can we register one of both, or would the v4 behavior just be "All CoAP nodes" again?

**Comment by petervanderstok** [comment]
Let's stick to all CoRE RDs address; specify a new address for v6, and equate all CoRE RD address equal to all CoAP nodes.

**Comment by petervanderstok** [comment]
Inserted text for "all RD" MC address registry, called MCD1 for the moment

**Comment by chrysn** [comment]
the equation would have turned out a bit complicated in the iana considerations (either it'd have spread the text around or we'd be aliasing multicast addresses), going with a dedicated address. See https://github.com/core-wg/resource-directory/issues/215 and today's CoRE chat logs.
