### ISSUE TITLE
Groups and domains

### ISSUE THREAD

**Issue by chrysn** [core-wg/resource-directory#88]
Brought up by Jim [on the mailing list](https://mailarchive.ietf.org/arch/msg/core/puP0Nv8sZnL-hW5vKQvCUvAaGRw):

> When registering groups, is there a requirement that all of the endpoints be in the same domain as the group is?

[Christian] That's the idea implied in the hierarchy, but probably answered better by Michael or Peter who use the domain concept more than I do.

[Peter] My cut feeling is "no". Groups may be part of other domains than the contributing endpoints. One might think of domain hierarchies. e.g. endpoint in room domains, multicast in enveloping corridor domain. I prefer to leave this to users of RD and not add extra rules.

**Comment by chrysn** [comment]
Then we should update figure "The resource directory information hierarchy" to not include the domains any more (I did preliminarily on the slides for IETF100). The figure is then a subset of the E-R model (without the resource-directory itself, and without all the attributes), but still has merit for overview.

And add a paragraph to "Register a group" (note to self: create PR, and change wording of "used to configure groups" to avoid mixing policy-style configuration with day-to-day operations like creating and changing groups)

> This specification does not require that the endpoints belong to the same domain as the group, but a Resource Directory implementation can impose requirements on the domains of groups and endpoints depending on its configuration.

**Comment by petervanderstok** [comment]
changed in my version as indicated above. Domain should have been removed earlier already from figure 2.
