### ISSUE TITLE
Add "ins" and "exp" link attributes

### ISSUE THREAD

**Issue by mjkoster** [core-wg/resource-directory#9]
"ins" (instance ID) is used to differentiate between two links which are otherwise indistinguishable. It is a text value which should be restricted to a maximum 63 octets.

"exp"is an attribute which provides a hint that the link may be exported to other RDs or other discovery services like DNS-SD

**Comment by petervanderstok** [comment]
What about an example how to use them? Can be connected to the dns-sd 
discovery of RD

Peter

Michael Koster schreef op 2017-03-30 08:15:

**Comment by chrysn** [comment]
I'm currently preparing that branch based on the -09 version.

**Comment by chrysn** [comment]
As mentioned in #11, this can be done in DNS-SD and is not needed here.
