### ISSUE TITLE
Interactions of the "con" attribute

### ISSUE THREAD

**Issue by jimsch** [core-wg/resource-directory#90]
A number of questions about the "con" attribute.

1.  Can it appear in a link during registration or is it just synthesized by the RD on lookup of resources?
If yes,
2.  Is the value of "con" on the resource link modified by changing the "con" value on the endpoint?  Does it make a difference if the value on the resource matches the old value on the endpoint

**Comment by chrysn** [comment]
If there is a con in one of the resource links, that has no semantics in RD and is not modified and simply passed through. We ascribe semantics only to the `con` target attribute of links to (endpoint or group) registration resources. There is no registry where we could claim that name for generic links.

A link only "has" a con in that it is a link of a particular endpoint, which has a con. That is what gets used for populating a relative anchor, and that is also available for querying at `/lkp/res?con=...`. If a link has a `con` of its own, that should only have two effects:

* It confuses human readers who might think that this con is out of place.
* It creates false positive matches in `/lkp/res?con=...` queries. False positives in such lookups are always a possibility given that we don't want to implement a powerful query language. We could consider enforcing the lookup level for some attributes (eg. say that `con` is never checked against a resource link attribute, making those attributes unqueriable), but I think that would be overkill.

(I hope that answers both questions).

**Comment by jimsch** [comment]
If a link has a con of it's own, would that mean that there are going to be two con attributes in the link when it is queried?

**Comment by chrysn** [comment]
No attribute of the endpoint is currently shown in the resource lookup; only the link's submitted con (whatever are the semantics of that) if shown.

**Comment by petervanderstok** [comment]
Added following text in section 5.3.2, Third-party registration

It should be noted that the value of the con parameter applies to all the links of the registration and has consequences for the anchor value of the individual links as exemplified in {{weblink}}. An eventual (currently non-existing) con attribute of the link is not affected by the value of con parameter in the registration.
