### ISSUE TITLE
multiple contexts per ep

### ISSUE THREAD

**Issue by petervanderstok** [core-wg/resource-directory#96]
proposal is to store multiple contexts in con attribute of the model.
questions to solve:
1) how do we register multiple contexts?
2) What are the filter attributes? (authority, scheme)
3) is there an ordering?

Ad1) suggestion is to specify multiple ?con=context1&con=context2&con=context3
Ad2) suggestion to use at="authority" instead of con="authority"; sc="scheme: seems useful indeed.
AD3) IMO: nay

**Comment by chrysn** [comment]
This is something protocol-negotiation will add; we agreed in the last group call that adding a forward reference is in order.
